/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class APIHeaderSection_MakeHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public APIHeaderSection_MakeHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(APIHeaderSection_MakeHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_APIHeaderSection_MakeHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public APIHeaderSection_MakeHeader(SWIGTYPE_p_Handle_StepData_StepModel model) {
    this(OccJavaJNI.new_APIHeaderSection_MakeHeader(SWIGTYPE_p_Handle_StepData_StepModel.getCPtr(model)), true);
  }

  public void setName(SWIGTYPE_p_Handle_TCollection_HAsciiString aName) {
    OccJavaJNI.APIHeaderSection_MakeHeader_setName(swigCPtr, this, SWIGTYPE_p_Handle_TCollection_HAsciiString.getCPtr(aName));
  }

  public void setAuthorValue(int num, SWIGTYPE_p_Handle_TCollection_HAsciiString aAuthor) {
    OccJavaJNI.APIHeaderSection_MakeHeader_setAuthorValue(swigCPtr, this, num, SWIGTYPE_p_Handle_TCollection_HAsciiString.getCPtr(aAuthor));
  }

  public void setOrganizationValue(int num, SWIGTYPE_p_Handle_TCollection_HAsciiString aOrganization) {
    OccJavaJNI.APIHeaderSection_MakeHeader_setOrganizationValue(swigCPtr, this, num, SWIGTYPE_p_Handle_TCollection_HAsciiString.getCPtr(aOrganization));
  }

  public void setOriginatingSystem(SWIGTYPE_p_Handle_TCollection_HAsciiString aOriginatingSystem) {
    OccJavaJNI.APIHeaderSection_MakeHeader_setOriginatingSystem(swigCPtr, this, SWIGTYPE_p_Handle_TCollection_HAsciiString.getCPtr(aOriginatingSystem));
  }

  public void setDescriptionValue(int num, SWIGTYPE_p_Handle_TCollection_HAsciiString description) {
    OccJavaJNI.APIHeaderSection_MakeHeader_setDescriptionValue(swigCPtr, this, num, SWIGTYPE_p_Handle_TCollection_HAsciiString.getCPtr(description));
  }

}
