/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_NormalProjection extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepOffsetAPI_NormalProjection(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_NormalProjection_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_NormalProjection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_NormalProjection(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_NormalProjection() {
    this(OccJavaJNI.new_BRepOffsetAPI_NormalProjection__SWIG_0(), true);
  }

  public BRepOffsetAPI_NormalProjection(TopoDS_Shape S) {
    this(OccJavaJNI.new_BRepOffsetAPI_NormalProjection__SWIG_1(TopoDS_Shape.getCPtr(S), S), true);
  }

  public void init(TopoDS_Shape S) {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_init(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
  }

  public void add(TopoDS_Shape ToProj) {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_add(swigCPtr, this, TopoDS_Shape.getCPtr(ToProj), ToProj);
  }

  public void setParams(double Tol3D, double Tol2D, GeomAbs_Shape InternalContinuity, int MaxDegree, int MaxSeg) {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_setParams(swigCPtr, this, Tol3D, Tol2D, InternalContinuity.swigValue(), MaxDegree, MaxSeg);
  }

  public void setMaxDistance(double MaxDist) {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_setMaxDistance(swigCPtr, this, MaxDist);
  }

  public void setLimit(boolean FaceBoundaries) {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_setLimit__SWIG_0(swigCPtr, this, FaceBoundaries);
  }

  public void setLimit() {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_setLimit__SWIG_1(swigCPtr, this);
  }

  public void compute3d(boolean With3d) {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_compute3d__SWIG_0(swigCPtr, this, With3d);
  }

  public void compute3d() {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_compute3d__SWIG_1(swigCPtr, this);
  }

  public void build() {
    OccJavaJNI.BRepOffsetAPI_NormalProjection_build(swigCPtr, this);
  }

  public boolean isDone() {
	return OccJavaJNI.BRepOffsetAPI_NormalProjection_isDone(swigCPtr, this);
}

  public TopoDS_Shape projection() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_NormalProjection_projection(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape couple(TopoDS_Edge E) {
    long cPtr = OccJavaJNI.BRepOffsetAPI_NormalProjection_couple(swigCPtr, this, TopoDS_Edge.getCPtr(E), E);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape[] generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_NormalProjection_generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public TopoDS_Shape ancestor(TopoDS_Edge E) {
    long cPtr = OccJavaJNI.BRepOffsetAPI_NormalProjection_ancestor(swigCPtr, this, TopoDS_Edge.getCPtr(E), E);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public boolean buildWire(SWIGTYPE_p_TopTools_ListOfShape Liste) {
	return OccJavaJNI.BRepOffsetAPI_NormalProjection_buildWire(swigCPtr, this, SWIGTYPE_p_TopTools_ListOfShape.getCPtr(Liste));
}

}
