/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepBuilderAPI_GTransform extends BRepBuilderAPI_ModifyShape {
  private long swigCPtr;

  public BRepBuilderAPI_GTransform(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepBuilderAPI_GTransform_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepBuilderAPI_GTransform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepBuilderAPI_GTransform(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepBuilderAPI_GTransform(GP_GTrsf T) {
    this(OccJavaJNI.new_BRepBuilderAPI_GTransform__SWIG_0(GP_GTrsf.getCPtr(T), T), true);
  }

  public BRepBuilderAPI_GTransform(TopoDS_Shape S, GP_GTrsf T, boolean Copy) {
    this(OccJavaJNI.new_BRepBuilderAPI_GTransform__SWIG_1(TopoDS_Shape.getCPtr(S), S, GP_GTrsf.getCPtr(T), T, Copy), true);
  }

  public BRepBuilderAPI_GTransform(TopoDS_Shape S, GP_GTrsf T) {
    this(OccJavaJNI.new_BRepBuilderAPI_GTransform__SWIG_2(TopoDS_Shape.getCPtr(S), S, GP_GTrsf.getCPtr(T), T), true);
  }

  public void Perform(TopoDS_Shape S, boolean Copy) {
    OccJavaJNI.BRepBuilderAPI_GTransform_Perform__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(S), S, Copy);
  }

  public void Perform(TopoDS_Shape S) {
    OccJavaJNI.BRepBuilderAPI_GTransform_Perform__SWIG_1(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
  }

  public TopoDS_Shape[] Modified(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepBuilderAPI_GTransform_Modified(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public TopoDS_Shape ModifiedShape(TopoDS_Shape S) {
    long cPtr = OccJavaJNI.BRepBuilderAPI_GTransform_ModifiedShape(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

}
