/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepBuilderAPI_Copy extends BRepBuilderAPI_ModifyShape {
  private long swigCPtr;

  public BRepBuilderAPI_Copy(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepBuilderAPI_Copy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepBuilderAPI_Copy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepBuilderAPI_Copy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepBuilderAPI_Copy() {
    this(OccJavaJNI.new_BRepBuilderAPI_Copy__SWIG_0(), true);
  }

  public BRepBuilderAPI_Copy(TopoDS_Shape S, boolean copyGeom) {
    this(OccJavaJNI.new_BRepBuilderAPI_Copy__SWIG_1(TopoDS_Shape.getCPtr(S), S, copyGeom), true);
  }

  public BRepBuilderAPI_Copy(TopoDS_Shape S) {
    this(OccJavaJNI.new_BRepBuilderAPI_Copy__SWIG_2(TopoDS_Shape.getCPtr(S), S), true);
  }

  public void Perform(TopoDS_Shape S, boolean copyGeom) {
    OccJavaJNI.BRepBuilderAPI_Copy_Perform__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(S), S, copyGeom);
  }

  public void Perform(TopoDS_Shape S) {
    OccJavaJNI.BRepBuilderAPI_Copy_Perform__SWIG_1(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
  }

}
