/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_Draft {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_Draft(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_Draft obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_Draft(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_Draft(TopoDS_Shape Shape, double[] Dir, double Angle) {
    this(OccJavaJNI.new_BRepFill_Draft(TopoDS_Shape.getCPtr(Shape), Shape, Dir, Angle), true);
  }

  public void SetOptions(BRepFill_TransitionStyle Style, double AngleMin, double AngleMax) {
    OccJavaJNI.BRepFill_Draft_SetOptions__SWIG_0(swigCPtr, this, Style.swigValue(), AngleMin, AngleMax);
  }

  public void SetOptions(BRepFill_TransitionStyle Style, double AngleMin) {
    OccJavaJNI.BRepFill_Draft_SetOptions__SWIG_1(swigCPtr, this, Style.swigValue(), AngleMin);
  }

  public void SetOptions(BRepFill_TransitionStyle Style) {
    OccJavaJNI.BRepFill_Draft_SetOptions__SWIG_2(swigCPtr, this, Style.swigValue());
  }

  public void SetOptions() {
    OccJavaJNI.BRepFill_Draft_SetOptions__SWIG_3(swigCPtr, this);
  }

  public void SetDraft(boolean IsInternal) {
    OccJavaJNI.BRepFill_Draft_SetDraft__SWIG_0(swigCPtr, this, IsInternal);
  }

  public void SetDraft() {
    OccJavaJNI.BRepFill_Draft_SetDraft__SWIG_1(swigCPtr, this);
  }

  public void Perform(double LengthMax) {
    OccJavaJNI.BRepFill_Draft_Perform__SWIG_0(swigCPtr, this, LengthMax);
  }

  public void Perform(Geom_Surface Surface, boolean KeepInsideSurface) {
    OccJavaJNI.BRepFill_Draft_Perform__SWIG_1(swigCPtr, this, Geom_Surface.getCPtr(Surface), Surface, KeepInsideSurface);
  }

  public void Perform(Geom_Surface Surface) {
    OccJavaJNI.BRepFill_Draft_Perform__SWIG_2(swigCPtr, this, Geom_Surface.getCPtr(Surface), Surface);
  }

  public void Perform(TopoDS_Shape StopShape, boolean KeepOutSide) {
    OccJavaJNI.BRepFill_Draft_Perform__SWIG_3(swigCPtr, this, TopoDS_Shape.getCPtr(StopShape), StopShape, KeepOutSide);
  }

  public void Perform(TopoDS_Shape StopShape) {
    OccJavaJNI.BRepFill_Draft_Perform__SWIG_4(swigCPtr, this, TopoDS_Shape.getCPtr(StopShape), StopShape);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepFill_Draft_IsDone(swigCPtr, this);
}

  public TopoDS_Shell Shell() {
    return new TopoDS_Shell(OccJavaJNI.BRepFill_Draft_Shell(swigCPtr, this), true);
  }

  public TopoDS_Shape[] Generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFill_Draft_Generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public TopoDS_Shape Shape() {
    long cPtr = OccJavaJNI.BRepFill_Draft_Shape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

}
