/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_MakePipeShell extends BRepPrimAPI_MakeSweep {
  private long swigCPtr;

  public BRepOffsetAPI_MakePipeShell(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_MakePipeShell_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_MakePipeShell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_MakePipeShell(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_MakePipeShell(TopoDS_Wire Spine) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakePipeShell(TopoDS_Wire.getCPtr(Spine), Spine), true);
  }

  public void SetMode(boolean IsFrenet) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_0(swigCPtr, this, IsFrenet);
  }

  public void SetMode() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_1(swigCPtr, this);
  }

  public void SetMode(double[] Axe) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_2(swigCPtr, this, Axe);
  }

  public boolean SetMode(TopoDS_Shape SpineSupport) {
	return OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_3(swigCPtr, this, TopoDS_Shape.getCPtr(SpineSupport), SpineSupport);
}

  public void SetMode(TopoDS_Wire AuxiliarySpine, boolean CurvilinearEquivalence, boolean KeepContact) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_4(swigCPtr, this, TopoDS_Wire.getCPtr(AuxiliarySpine), AuxiliarySpine, CurvilinearEquivalence, KeepContact);
  }

  public void SetMode(TopoDS_Wire AuxiliarySpine, boolean CurvilinearEquivalence) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_5(swigCPtr, this, TopoDS_Wire.getCPtr(AuxiliarySpine), AuxiliarySpine, CurvilinearEquivalence);
  }

  public void Add(TopoDS_Shape Profile, boolean WithContact, boolean WithCorrection) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Add__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, WithContact, WithCorrection);
  }

  public void Add(TopoDS_Shape Profile, boolean WithContact) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Add__SWIG_1(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, WithContact);
  }

  public void Add(TopoDS_Shape Profile) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Add__SWIG_2(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile);
  }

  public void Add(TopoDS_Shape Profile, TopoDS_Vertex Location, boolean WithContact, boolean WithCorrection) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Add__SWIG_3(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(Location), Location, WithContact, WithCorrection);
  }

  public void Add(TopoDS_Shape Profile, TopoDS_Vertex Location, boolean WithContact) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Add__SWIG_4(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(Location), Location, WithContact);
  }

  public void Add(TopoDS_Shape Profile, TopoDS_Vertex Location) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Add__SWIG_5(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(Location), Location);
  }

  public void Delete(TopoDS_Shape Profile) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Delete(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile);
  }

  public boolean IsReady() {
	return OccJavaJNI.BRepOffsetAPI_MakePipeShell_IsReady(swigCPtr, this);
}

  public BRepBuilderAPI_PipeError GetStatus() {
    return BRepBuilderAPI_PipeError.swigToEnum(OccJavaJNI.BRepOffsetAPI_MakePipeShell_GetStatus(swigCPtr, this));
  }

  public void SetTolerance(double Tol3d, double BoundTol, double TolAngular) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetTolerance__SWIG_0(swigCPtr, this, Tol3d, BoundTol, TolAngular);
  }

  public void SetTolerance(double Tol3d, double BoundTol) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetTolerance__SWIG_1(swigCPtr, this, Tol3d, BoundTol);
  }

  public void SetTolerance(double Tol3d) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetTolerance__SWIG_2(swigCPtr, this, Tol3d);
  }

  public void SetTolerance() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetTolerance__SWIG_3(swigCPtr, this);
  }

  public void SetTransitionMode(BRepBuilderAPI_TransitionMode Mode) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetTransitionMode__SWIG_0(swigCPtr, this, Mode.swigValue());
  }

  public void SetTransitionMode() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetTransitionMode__SWIG_1(swigCPtr, this);
  }

  public void Simulate(int NumberOfSection, SWIGTYPE_p_TopTools_ListOfShape Result) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Simulate(swigCPtr, this, NumberOfSection, SWIGTYPE_p_TopTools_ListOfShape.getCPtr(Result));
  }

  public void Build() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Build(swigCPtr, this);
  }

  public boolean MakeSolid() {
	return OccJavaJNI.BRepOffsetAPI_MakePipeShell_MakeSolid(swigCPtr, this);
}

  public TopoDS_Shape FirstShape() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_MakePipeShell_FirstShape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape LastShape() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_MakePipeShell_LastShape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape[] Generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_MakePipeShell_Generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

}
