/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepMesh {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepMesh(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepMesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepMesh(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Mesh(TopoDS_Shape S, double d) {
    OccJavaJNI.BRepMesh_Mesh(swigCPtr, this, TopoDS_Shape.getCPtr(S), S, d);
  }

  public BRepMesh() {
    this(OccJavaJNI.new_BRepMesh(), true);
  }

}
