/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFeat_Form extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepFeat_Form(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepFeat_Form_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFeat_Form obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFeat_Form(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TopoDS_Shape[] Modified(TopoDS_Shape F) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFeat_Form_Modified(swigCPtr, this, TopoDS_Shape.getCPtr(F), F));
}

  public TopoDS_Shape[] Generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFeat_Form_Generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public boolean IsDeleted(TopoDS_Shape S) {
	return OccJavaJNI.BRepFeat_Form_IsDeleted(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
}

  public void BasisShapeValid() {
    OccJavaJNI.BRepFeat_Form_BasisShapeValid(swigCPtr, this);
  }

  public void GeneratedShapeValid() {
    OccJavaJNI.BRepFeat_Form_GeneratedShapeValid(swigCPtr, this);
  }

  public void ShapeFromValid() {
    OccJavaJNI.BRepFeat_Form_ShapeFromValid(swigCPtr, this);
  }

  public void ShapeUntilValid() {
    OccJavaJNI.BRepFeat_Form_ShapeUntilValid(swigCPtr, this);
  }

  public void GluedFacesValid() {
    OccJavaJNI.BRepFeat_Form_GluedFacesValid(swigCPtr, this);
  }

  public void SketchFaceValid() {
    OccJavaJNI.BRepFeat_Form_SketchFaceValid(swigCPtr, this);
  }

  public void PerfSelectionValid() {
    OccJavaJNI.BRepFeat_Form_PerfSelectionValid(swigCPtr, this);
  }

}
