/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_MakeFilling extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepOffsetAPI_MakeFilling(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_MakeFilling_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_MakeFilling obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_MakeFilling(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng, double TolCurv, int MaxDeg, int MaxSegments) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_0(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng, TolCurv, MaxDeg, MaxSegments), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng, double TolCurv, int MaxDeg) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_1(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng, TolCurv, MaxDeg), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng, double TolCurv) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_2(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng, TolCurv), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_3(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_4(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_5(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_6(Degree, NbPtsOnCur, NbIter, Anisotropie), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur, int NbIter) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_7(Degree, NbPtsOnCur, NbIter), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree, int NbPtsOnCur) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_8(Degree, NbPtsOnCur), true);
  }

  public BRepOffsetAPI_MakeFilling(int Degree) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_9(Degree), true);
  }

  public BRepOffsetAPI_MakeFilling() {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeFilling__SWIG_10(), true);
  }

  public void SetConstrParam(double Tol2d, double Tol3d, double TolAng, double TolCurv) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetConstrParam__SWIG_0(swigCPtr, this, Tol2d, Tol3d, TolAng, TolCurv);
  }

  public void SetConstrParam(double Tol2d, double Tol3d, double TolAng) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetConstrParam__SWIG_1(swigCPtr, this, Tol2d, Tol3d, TolAng);
  }

  public void SetConstrParam(double Tol2d, double Tol3d) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetConstrParam__SWIG_2(swigCPtr, this, Tol2d, Tol3d);
  }

  public void SetConstrParam(double Tol2d) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetConstrParam__SWIG_3(swigCPtr, this, Tol2d);
  }

  public void SetConstrParam() {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetConstrParam__SWIG_4(swigCPtr, this);
  }

  public void SetResolParam(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetResolParam__SWIG_0(swigCPtr, this, Degree, NbPtsOnCur, NbIter, Anisotropie);
  }

  public void SetResolParam(int Degree, int NbPtsOnCur, int NbIter) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetResolParam__SWIG_1(swigCPtr, this, Degree, NbPtsOnCur, NbIter);
  }

  public void SetResolParam(int Degree, int NbPtsOnCur) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetResolParam__SWIG_2(swigCPtr, this, Degree, NbPtsOnCur);
  }

  public void SetResolParam(int Degree) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetResolParam__SWIG_3(swigCPtr, this, Degree);
  }

  public void SetResolParam() {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetResolParam__SWIG_4(swigCPtr, this);
  }

  public void SetApproxParam(int MaxDeg, int MaxSegments) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetApproxParam__SWIG_0(swigCPtr, this, MaxDeg, MaxSegments);
  }

  public void SetApproxParam(int MaxDeg) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetApproxParam__SWIG_1(swigCPtr, this, MaxDeg);
  }

  public void SetApproxParam() {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_SetApproxParam__SWIG_2(swigCPtr, this);
  }

  public void LoadInitSurface(TopoDS_Face Surf) {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_LoadInitSurface(swigCPtr, this, TopoDS_Face.getCPtr(Surf), Surf);
  }

  public int Add(TopoDS_Edge Constr, GeomAbs_Shape Order, boolean IsBound) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_0(swigCPtr, this, TopoDS_Edge.getCPtr(Constr), Constr, Order.swigValue(), IsBound);
  }

  public int Add(TopoDS_Edge Constr, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_1(swigCPtr, this, TopoDS_Edge.getCPtr(Constr), Constr, Order.swigValue());
  }

  public int Add(TopoDS_Edge Constr, TopoDS_Face Support, GeomAbs_Shape Order, boolean IsBound) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_2(swigCPtr, this, TopoDS_Edge.getCPtr(Constr), Constr, TopoDS_Face.getCPtr(Support), Support, Order.swigValue(), IsBound);
  }

  public int Add(TopoDS_Edge Constr, TopoDS_Face Support, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_3(swigCPtr, this, TopoDS_Edge.getCPtr(Constr), Constr, TopoDS_Face.getCPtr(Support), Support, Order.swigValue());
  }

  public int Add(TopoDS_Face Support, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_4(swigCPtr, this, TopoDS_Face.getCPtr(Support), Support, Order.swigValue());
  }

  public int Add(double[] Point) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_5(swigCPtr, this, Point);
  }

  public int Add(double U, double V, TopoDS_Face Support, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_Add__SWIG_6(swigCPtr, this, U, V, TopoDS_Face.getCPtr(Support), Support, Order.swigValue());
  }

  public void Build() {
    OccJavaJNI.BRepOffsetAPI_MakeFilling_Build(swigCPtr, this);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepOffsetAPI_MakeFilling_IsDone(swigCPtr, this);
}

  public double G0Error() {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_G0Error__SWIG_0(swigCPtr, this);
  }

  public double G1Error() {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_G1Error__SWIG_0(swigCPtr, this);
  }

  public double G2Error() {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_G2Error__SWIG_0(swigCPtr, this);
  }

  public double G0Error(int Index) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_G0Error__SWIG_1(swigCPtr, this, Index);
  }

  public double G1Error(int Index) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_G1Error__SWIG_1(swigCPtr, this, Index);
  }

  public double G2Error(int Index) {
    return OccJavaJNI.BRepOffsetAPI_MakeFilling_G2Error__SWIG_1(swigCPtr, this, Index);
  }

}
