/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_MakeDraft extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepOffsetAPI_MakeDraft(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_MakeDraft_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_MakeDraft obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_MakeDraft(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_MakeDraft(TopoDS_Shape Shape, double[] Dir, double Angle) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeDraft(TopoDS_Shape.getCPtr(Shape), Shape, Dir, Angle), true);
  }

  public void SetOptions(BRepBuilderAPI_TransitionMode Style, double AngleMin, double AngleMax) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_SetOptions__SWIG_0(swigCPtr, this, Style.swigValue(), AngleMin, AngleMax);
  }

  public void SetOptions(BRepBuilderAPI_TransitionMode Style, double AngleMin) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_SetOptions__SWIG_1(swigCPtr, this, Style.swigValue(), AngleMin);
  }

  public void SetOptions(BRepBuilderAPI_TransitionMode Style) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_SetOptions__SWIG_2(swigCPtr, this, Style.swigValue());
  }

  public void SetOptions() {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_SetOptions__SWIG_3(swigCPtr, this);
  }

  public void SetDraft(boolean IsInternal) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_SetDraft__SWIG_0(swigCPtr, this, IsInternal);
  }

  public void SetDraft() {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_SetDraft__SWIG_1(swigCPtr, this);
  }

  public void Perform(double LengthMax) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_Perform__SWIG_0(swigCPtr, this, LengthMax);
  }

  public void Perform(Geom_Surface Surface, boolean KeepInsideSurface) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_Perform__SWIG_1(swigCPtr, this, Geom_Surface.getCPtr(Surface), Surface, KeepInsideSurface);
  }

  public void Perform(Geom_Surface Surface) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_Perform__SWIG_2(swigCPtr, this, Geom_Surface.getCPtr(Surface), Surface);
  }

  public void Perform(TopoDS_Shape StopShape, boolean KeepOutSide) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_Perform__SWIG_3(swigCPtr, this, TopoDS_Shape.getCPtr(StopShape), StopShape, KeepOutSide);
  }

  public void Perform(TopoDS_Shape StopShape) {
    OccJavaJNI.BRepOffsetAPI_MakeDraft_Perform__SWIG_4(swigCPtr, this, TopoDS_Shape.getCPtr(StopShape), StopShape);
  }

  public TopoDS_Shell Shell() {
    return new TopoDS_Shell(OccJavaJNI.BRepOffsetAPI_MakeDraft_Shell(swigCPtr, this), true);
  }

  public TopoDS_Shape[] Generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_MakeDraft_Generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

}
