/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepBuilderAPI_FindPlane {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepBuilderAPI_FindPlane(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepBuilderAPI_FindPlane obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepBuilderAPI_FindPlane(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepBuilderAPI_FindPlane() {
    this(OccJavaJNI.new_BRepBuilderAPI_FindPlane__SWIG_0(), true);
  }

  public BRepBuilderAPI_FindPlane(TopoDS_Shape S, double Tol) {
    this(OccJavaJNI.new_BRepBuilderAPI_FindPlane__SWIG_1(TopoDS_Shape.getCPtr(S), S, Tol), true);
  }

  public BRepBuilderAPI_FindPlane(TopoDS_Shape S) {
    this(OccJavaJNI.new_BRepBuilderAPI_FindPlane__SWIG_2(TopoDS_Shape.getCPtr(S), S), true);
  }

  public void Init(TopoDS_Shape S, double Tol) {
    OccJavaJNI.BRepBuilderAPI_FindPlane_Init__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(S), S, Tol);
  }

  public void Init(TopoDS_Shape S) {
    OccJavaJNI.BRepBuilderAPI_FindPlane_Init__SWIG_1(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
  }

  public boolean Found() {
	return OccJavaJNI.BRepBuilderAPI_FindPlane_Found(swigCPtr, this);
}

  public Geom_Plane Plane() {
    return new Geom_Plane(OccJavaJNI.BRepBuilderAPI_FindPlane_Plane(swigCPtr, this), true);
  }

}
