/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepBuilderAPI_MakePolygon extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepBuilderAPI_MakePolygon(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepBuilderAPI_MakePolygon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepBuilderAPI_MakePolygon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepBuilderAPI_MakePolygon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepBuilderAPI_MakePolygon() {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_0(), true);
  }

  public BRepBuilderAPI_MakePolygon(double[] P1, double[] P2) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_1(P1, P2), true);
  }

  public BRepBuilderAPI_MakePolygon(double[] P1, double[] P2, double[] P3, boolean Close) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_2(P1, P2, P3, Close), true);
  }

  public BRepBuilderAPI_MakePolygon(double[] P1, double[] P2, double[] P3) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_3(P1, P2, P3), true);
  }

  public BRepBuilderAPI_MakePolygon(double[] P1, double[] P2, double[] P3, double[] P4, boolean Close) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_4(P1, P2, P3, P4, Close), true);
  }

  public BRepBuilderAPI_MakePolygon(double[] P1, double[] P2, double[] P3, double[] P4) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_5(P1, P2, P3, P4), true);
  }

  public BRepBuilderAPI_MakePolygon(TopoDS_Vertex V1, TopoDS_Vertex V2) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_6(TopoDS_Vertex.getCPtr(V1), V1, TopoDS_Vertex.getCPtr(V2), V2), true);
  }

  public BRepBuilderAPI_MakePolygon(TopoDS_Vertex V1, TopoDS_Vertex V2, TopoDS_Vertex V3, boolean Close) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_7(TopoDS_Vertex.getCPtr(V1), V1, TopoDS_Vertex.getCPtr(V2), V2, TopoDS_Vertex.getCPtr(V3), V3, Close), true);
  }

  public BRepBuilderAPI_MakePolygon(TopoDS_Vertex V1, TopoDS_Vertex V2, TopoDS_Vertex V3) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_8(TopoDS_Vertex.getCPtr(V1), V1, TopoDS_Vertex.getCPtr(V2), V2, TopoDS_Vertex.getCPtr(V3), V3), true);
  }

  public BRepBuilderAPI_MakePolygon(TopoDS_Vertex V1, TopoDS_Vertex V2, TopoDS_Vertex V3, TopoDS_Vertex V4, boolean Close) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_9(TopoDS_Vertex.getCPtr(V1), V1, TopoDS_Vertex.getCPtr(V2), V2, TopoDS_Vertex.getCPtr(V3), V3, TopoDS_Vertex.getCPtr(V4), V4, Close), true);
  }

  public BRepBuilderAPI_MakePolygon(TopoDS_Vertex V1, TopoDS_Vertex V2, TopoDS_Vertex V3, TopoDS_Vertex V4) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakePolygon__SWIG_10(TopoDS_Vertex.getCPtr(V1), V1, TopoDS_Vertex.getCPtr(V2), V2, TopoDS_Vertex.getCPtr(V3), V3, TopoDS_Vertex.getCPtr(V4), V4), true);
  }

  public void Add(double[] P) {
    OccJavaJNI.BRepBuilderAPI_MakePolygon_Add__SWIG_0(swigCPtr, this, P);
  }

  public void Add(TopoDS_Vertex V) {
    OccJavaJNI.BRepBuilderAPI_MakePolygon_Add__SWIG_1(swigCPtr, this, TopoDS_Vertex.getCPtr(V), V);
  }

  public boolean Added() {
	return OccJavaJNI.BRepBuilderAPI_MakePolygon_Added(swigCPtr, this);
}

  public void Close() {
    OccJavaJNI.BRepBuilderAPI_MakePolygon_Close(swigCPtr, this);
  }

  public TopoDS_Vertex FirstVertex() {
    return new TopoDS_Vertex(OccJavaJNI.BRepBuilderAPI_MakePolygon_FirstVertex(swigCPtr, this), false);
  }

  public TopoDS_Vertex LastVertex() {
    return new TopoDS_Vertex(OccJavaJNI.BRepBuilderAPI_MakePolygon_LastVertex(swigCPtr, this), false);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepBuilderAPI_MakePolygon_IsDone(swigCPtr, this);
}

  public TopoDS_Edge Edge() {
    return new TopoDS_Edge(OccJavaJNI.BRepBuilderAPI_MakePolygon_Edge(swigCPtr, this), false);
  }

  public TopoDS_Wire Wire() {
    return new TopoDS_Wire(OccJavaJNI.BRepBuilderAPI_MakePolygon_Wire(swigCPtr, this), false);
  }

}
