/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepPrimAPI_MakeHalfSpace extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepPrimAPI_MakeHalfSpace(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepPrimAPI_MakeHalfSpace_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepPrimAPI_MakeHalfSpace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepPrimAPI_MakeHalfSpace(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepPrimAPI_MakeHalfSpace(TopoDS_Face Face, double[] RefPnt) {
    this(OccJavaJNI.new_BRepPrimAPI_MakeHalfSpace__SWIG_0(TopoDS_Face.getCPtr(Face), Face, RefPnt), true);
  }

  public BRepPrimAPI_MakeHalfSpace(TopoDS_Shell Shell, double[] RefPnt) {
    this(OccJavaJNI.new_BRepPrimAPI_MakeHalfSpace__SWIG_1(TopoDS_Shell.getCPtr(Shell), Shell, RefPnt), true);
  }

  public TopoDS_Solid Solid() {
    return new TopoDS_Solid(OccJavaJNI.BRepPrimAPI_MakeHalfSpace_Solid(swigCPtr, this), false);
  }

}
