/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_MakeOffsetShape extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepOffsetAPI_MakeOffsetShape(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_MakeOffsetShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_MakeOffsetShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_MakeOffsetShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_MakeOffsetShape() {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeOffsetShape__SWIG_0(), true);
  }

  public BRepOffsetAPI_MakeOffsetShape(TopoDS_Shape S, double Offset, double Tol, BRepOffset_Mode Mode, boolean Intersection, boolean SelfInter, GeomAbs_JoinType Join) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeOffsetShape__SWIG_1(TopoDS_Shape.getCPtr(S), S, Offset, Tol, Mode.swigValue(), Intersection, SelfInter, Join.swigValue()), true);
  }

  public BRepOffsetAPI_MakeOffsetShape(TopoDS_Shape S, double Offset, double Tol, BRepOffset_Mode Mode, boolean Intersection, boolean SelfInter) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeOffsetShape__SWIG_2(TopoDS_Shape.getCPtr(S), S, Offset, Tol, Mode.swigValue(), Intersection, SelfInter), true);
  }

  public BRepOffsetAPI_MakeOffsetShape(TopoDS_Shape S, double Offset, double Tol, BRepOffset_Mode Mode, boolean Intersection) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeOffsetShape__SWIG_3(TopoDS_Shape.getCPtr(S), S, Offset, Tol, Mode.swigValue(), Intersection), true);
  }

  public BRepOffsetAPI_MakeOffsetShape(TopoDS_Shape S, double Offset, double Tol, BRepOffset_Mode Mode) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeOffsetShape__SWIG_4(TopoDS_Shape.getCPtr(S), S, Offset, Tol, Mode.swigValue()), true);
  }

  public BRepOffsetAPI_MakeOffsetShape(TopoDS_Shape S, double Offset, double Tol) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeOffsetShape__SWIG_5(TopoDS_Shape.getCPtr(S), S, Offset, Tol), true);
  }

  public void Build() {
    OccJavaJNI.BRepOffsetAPI_MakeOffsetShape_Build(swigCPtr, this);
  }

  public TopoDS_Shape[] Generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_MakeOffsetShape_Generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public TopoDS_Shape[] GeneratedEdge(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_MakeOffsetShape_GeneratedEdge(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public GeomAbs_JoinType GetJoinType() {
    return GeomAbs_JoinType.swigToEnum(OccJavaJNI.BRepOffsetAPI_MakeOffsetShape_GetJoinType(swigCPtr, this));
  }

}
