/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_Pipe {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_Pipe(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_Pipe obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_Pipe(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_Pipe() {
    this(OccJavaJNI.new_BRepFill_Pipe__SWIG_0(), true);
  }

  public BRepFill_Pipe(TopoDS_Wire Spine, TopoDS_Shape Profile, boolean GeneratePartCase) {
    this(OccJavaJNI.new_BRepFill_Pipe__SWIG_1(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Shape.getCPtr(Profile), Profile, GeneratePartCase), true);
  }

  public BRepFill_Pipe(TopoDS_Wire Spine, TopoDS_Shape Profile) {
    this(OccJavaJNI.new_BRepFill_Pipe__SWIG_2(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Shape.getCPtr(Profile), Profile), true);
  }

  public void Perform(TopoDS_Wire Spine, TopoDS_Shape Profile, boolean GeneratePartCase) {
    OccJavaJNI.BRepFill_Pipe_Perform__SWIG_0(swigCPtr, this, TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Shape.getCPtr(Profile), Profile, GeneratePartCase);
  }

  public void Perform(TopoDS_Wire Spine, TopoDS_Shape Profile) {
    OccJavaJNI.BRepFill_Pipe_Perform__SWIG_1(swigCPtr, this, TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Shape.getCPtr(Profile), Profile);
  }

  public TopoDS_Shape Spine() {
    long cPtr = OccJavaJNI.BRepFill_Pipe_Spine(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape Profile() {
    long cPtr = OccJavaJNI.BRepFill_Pipe_Profile(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape Shape() {
    long cPtr = OccJavaJNI.BRepFill_Pipe_Shape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape FirstShape() {
    long cPtr = OccJavaJNI.BRepFill_Pipe_FirstShape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape LastShape() {
    long cPtr = OccJavaJNI.BRepFill_Pipe_LastShape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Face Face(TopoDS_Edge ESpine, TopoDS_Edge EProfile) {
    return new TopoDS_Face(OccJavaJNI.BRepFill_Pipe_Face(swigCPtr, this, TopoDS_Edge.getCPtr(ESpine), ESpine, TopoDS_Edge.getCPtr(EProfile), EProfile), true);
  }

  public TopoDS_Edge Edge(TopoDS_Edge ESpine, TopoDS_Vertex VProfile) {
    return new TopoDS_Edge(OccJavaJNI.BRepFill_Pipe_Edge(swigCPtr, this, TopoDS_Edge.getCPtr(ESpine), ESpine, TopoDS_Vertex.getCPtr(VProfile), VProfile), true);
  }

  public TopoDS_Shape Section(TopoDS_Vertex VSpine) {
    long cPtr = OccJavaJNI.BRepFill_Pipe_Section(swigCPtr, this, TopoDS_Vertex.getCPtr(VSpine), VSpine);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Wire PipeLine(double[] Point) {
    return new TopoDS_Wire(OccJavaJNI.BRepFill_Pipe_PipeLine(swigCPtr, this, Point), true);
  }

}
