/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_Generator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_Generator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_Generator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_Generator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_Generator() {
    this(OccJavaJNI.new_BRepFill_Generator(), true);
  }

  public void AddWire(TopoDS_Wire Wire) {
    OccJavaJNI.BRepFill_Generator_AddWire(swigCPtr, this, TopoDS_Wire.getCPtr(Wire), Wire);
  }

  public void Perform() {
    OccJavaJNI.BRepFill_Generator_Perform(swigCPtr, this);
  }

  public TopoDS_Shell Shell() {
    return new TopoDS_Shell(OccJavaJNI.BRepFill_Generator_Shell(swigCPtr, this), false);
  }

  public TopoDS_Shape[] GeneratedShapes(TopoDS_Shape SSection) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFill_Generator_GeneratedShapes(swigCPtr, this, TopoDS_Shape.getCPtr(SSection), SSection));
}

}
