/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFilletAPI_MakeFillet2d extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepFilletAPI_MakeFillet2d(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepFilletAPI_MakeFillet2d_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFilletAPI_MakeFillet2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFilletAPI_MakeFillet2d(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepFilletAPI_MakeFillet2d() {
    this(OccJavaJNI.new_BRepFilletAPI_MakeFillet2d__SWIG_0(), true);
  }

  public BRepFilletAPI_MakeFillet2d(TopoDS_Face F) {
    this(OccJavaJNI.new_BRepFilletAPI_MakeFillet2d__SWIG_1(TopoDS_Face.getCPtr(F), F), true);
  }

  public void Init(TopoDS_Face F) {
    OccJavaJNI.BRepFilletAPI_MakeFillet2d_Init__SWIG_0(swigCPtr, this, TopoDS_Face.getCPtr(F), F);
  }

  public void Init(TopoDS_Face RefFace, TopoDS_Face ModFace) {
    OccJavaJNI.BRepFilletAPI_MakeFillet2d_Init__SWIG_1(swigCPtr, this, TopoDS_Face.getCPtr(RefFace), RefFace, TopoDS_Face.getCPtr(ModFace), ModFace);
  }

  public TopoDS_Edge AddFillet(TopoDS_Vertex V, double Radius) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_AddFillet(swigCPtr, this, TopoDS_Vertex.getCPtr(V), V, Radius), true);
  }

  public TopoDS_Edge ModifyFillet(TopoDS_Edge Fillet, double Radius) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_ModifyFillet(swigCPtr, this, TopoDS_Edge.getCPtr(Fillet), Fillet, Radius), true);
  }

  public TopoDS_Vertex RemoveFillet(TopoDS_Edge Fillet) {
    return new TopoDS_Vertex(OccJavaJNI.BRepFilletAPI_MakeFillet2d_RemoveFillet(swigCPtr, this, TopoDS_Edge.getCPtr(Fillet), Fillet), true);
  }

  public TopoDS_Edge AddChamfer(TopoDS_Edge E1, TopoDS_Edge E2, double D1, double D2) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_AddChamfer__SWIG_0(swigCPtr, this, TopoDS_Edge.getCPtr(E1), E1, TopoDS_Edge.getCPtr(E2), E2, D1, D2), true);
  }

  public TopoDS_Edge AddChamfer(TopoDS_Edge E, TopoDS_Vertex V, double D, double Ang) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_AddChamfer__SWIG_1(swigCPtr, this, TopoDS_Edge.getCPtr(E), E, TopoDS_Vertex.getCPtr(V), V, D, Ang), true);
  }

  public TopoDS_Edge ModifyChamfer(TopoDS_Edge Chamfer, TopoDS_Edge E1, TopoDS_Edge E2, double D1, double D2) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_ModifyChamfer__SWIG_0(swigCPtr, this, TopoDS_Edge.getCPtr(Chamfer), Chamfer, TopoDS_Edge.getCPtr(E1), E1, TopoDS_Edge.getCPtr(E2), E2, D1, D2), true);
  }

  public TopoDS_Edge ModifyChamfer(TopoDS_Edge Chamfer, TopoDS_Edge E, double D, double Ang) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_ModifyChamfer__SWIG_1(swigCPtr, this, TopoDS_Edge.getCPtr(Chamfer), Chamfer, TopoDS_Edge.getCPtr(E), E, D, Ang), true);
  }

  public TopoDS_Vertex RemoveChamfer(TopoDS_Edge Chamfer) {
    return new TopoDS_Vertex(OccJavaJNI.BRepFilletAPI_MakeFillet2d_RemoveChamfer(swigCPtr, this, TopoDS_Edge.getCPtr(Chamfer), Chamfer), true);
  }

  public boolean IsModified(TopoDS_Edge E) {
	return OccJavaJNI.BRepFilletAPI_MakeFillet2d_IsModified(swigCPtr, this, TopoDS_Edge.getCPtr(E), E);
}

  public int NbFillet() {
    return OccJavaJNI.BRepFilletAPI_MakeFillet2d_NbFillet(swigCPtr, this);
  }

  public int NbChamfer() {
    return OccJavaJNI.BRepFilletAPI_MakeFillet2d_NbChamfer(swigCPtr, this);
  }

  public TopoDS_Shape[] Modified(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFilletAPI_MakeFillet2d_Modified(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public int NbCurves() {
    return OccJavaJNI.BRepFilletAPI_MakeFillet2d_NbCurves(swigCPtr, this);
  }

  public TopoDS_Shape[] NewEdges(int I) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFilletAPI_MakeFillet2d_NewEdges(swigCPtr, this, I));
}

  public boolean HasDescendant(TopoDS_Edge E) {
	return OccJavaJNI.BRepFilletAPI_MakeFillet2d_HasDescendant(swigCPtr, this, TopoDS_Edge.getCPtr(E), E);
}

  public TopoDS_Edge DescendantEdge(TopoDS_Edge E) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_DescendantEdge(swigCPtr, this, TopoDS_Edge.getCPtr(E), E), false);
  }

  public TopoDS_Edge BasisEdge(TopoDS_Edge E) {
    return new TopoDS_Edge(OccJavaJNI.BRepFilletAPI_MakeFillet2d_BasisEdge(swigCPtr, this, TopoDS_Edge.getCPtr(E), E), false);
  }

  public void Build() {
    OccJavaJNI.BRepFilletAPI_MakeFillet2d_Build(swigCPtr, this);
  }

}
