/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_Filling {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_Filling(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_Filling obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_Filling(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng, double TolCurv, int MaxDeg, int MaxSegments) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_0(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng, TolCurv, MaxDeg, MaxSegments), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng, double TolCurv, int MaxDeg) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_1(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng, TolCurv, MaxDeg), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng, double TolCurv) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_2(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng, TolCurv), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d, double TolAng) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_3(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d, TolAng), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d, double Tol3d) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_4(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d, Tol3d), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie, double Tol2d) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_5(Degree, NbPtsOnCur, NbIter, Anisotropie, Tol2d), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_6(Degree, NbPtsOnCur, NbIter, Anisotropie), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur, int NbIter) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_7(Degree, NbPtsOnCur, NbIter), true);
  }

  public BRepFill_Filling(int Degree, int NbPtsOnCur) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_8(Degree, NbPtsOnCur), true);
  }

  public BRepFill_Filling(int Degree) {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_9(Degree), true);
  }

  public BRepFill_Filling() {
    this(OccJavaJNI.new_BRepFill_Filling__SWIG_10(), true);
  }

  public void SetConstrParam(double Tol2d, double Tol3d, double TolAng, double TolCurv) {
    OccJavaJNI.BRepFill_Filling_SetConstrParam__SWIG_0(swigCPtr, this, Tol2d, Tol3d, TolAng, TolCurv);
  }

  public void SetConstrParam(double Tol2d, double Tol3d, double TolAng) {
    OccJavaJNI.BRepFill_Filling_SetConstrParam__SWIG_1(swigCPtr, this, Tol2d, Tol3d, TolAng);
  }

  public void SetConstrParam(double Tol2d, double Tol3d) {
    OccJavaJNI.BRepFill_Filling_SetConstrParam__SWIG_2(swigCPtr, this, Tol2d, Tol3d);
  }

  public void SetConstrParam(double Tol2d) {
    OccJavaJNI.BRepFill_Filling_SetConstrParam__SWIG_3(swigCPtr, this, Tol2d);
  }

  public void SetConstrParam() {
    OccJavaJNI.BRepFill_Filling_SetConstrParam__SWIG_4(swigCPtr, this);
  }

  public void SetResolParam(int Degree, int NbPtsOnCur, int NbIter, boolean Anisotropie) {
    OccJavaJNI.BRepFill_Filling_SetResolParam__SWIG_0(swigCPtr, this, Degree, NbPtsOnCur, NbIter, Anisotropie);
  }

  public void SetResolParam(int Degree, int NbPtsOnCur, int NbIter) {
    OccJavaJNI.BRepFill_Filling_SetResolParam__SWIG_1(swigCPtr, this, Degree, NbPtsOnCur, NbIter);
  }

  public void SetResolParam(int Degree, int NbPtsOnCur) {
    OccJavaJNI.BRepFill_Filling_SetResolParam__SWIG_2(swigCPtr, this, Degree, NbPtsOnCur);
  }

  public void SetResolParam(int Degree) {
    OccJavaJNI.BRepFill_Filling_SetResolParam__SWIG_3(swigCPtr, this, Degree);
  }

  public void SetResolParam() {
    OccJavaJNI.BRepFill_Filling_SetResolParam__SWIG_4(swigCPtr, this);
  }

  public void SetApproxParam(int MaxDeg, int MaxSegments) {
    OccJavaJNI.BRepFill_Filling_SetApproxParam__SWIG_0(swigCPtr, this, MaxDeg, MaxSegments);
  }

  public void SetApproxParam(int MaxDeg) {
    OccJavaJNI.BRepFill_Filling_SetApproxParam__SWIG_1(swigCPtr, this, MaxDeg);
  }

  public void SetApproxParam() {
    OccJavaJNI.BRepFill_Filling_SetApproxParam__SWIG_2(swigCPtr, this);
  }

  public void LoadInitSurface(TopoDS_Face aFace) {
    OccJavaJNI.BRepFill_Filling_LoadInitSurface(swigCPtr, this, TopoDS_Face.getCPtr(aFace), aFace);
  }

  public int Add(TopoDS_Edge anEdge, GeomAbs_Shape Order, boolean IsBound) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_0(swigCPtr, this, TopoDS_Edge.getCPtr(anEdge), anEdge, Order.swigValue(), IsBound);
  }

  public int Add(TopoDS_Edge anEdge, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_1(swigCPtr, this, TopoDS_Edge.getCPtr(anEdge), anEdge, Order.swigValue());
  }

  public int Add(TopoDS_Edge anEdge, TopoDS_Face Support, GeomAbs_Shape Order, boolean IsBound) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_2(swigCPtr, this, TopoDS_Edge.getCPtr(anEdge), anEdge, TopoDS_Face.getCPtr(Support), Support, Order.swigValue(), IsBound);
  }

  public int Add(TopoDS_Edge anEdge, TopoDS_Face Support, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_3(swigCPtr, this, TopoDS_Edge.getCPtr(anEdge), anEdge, TopoDS_Face.getCPtr(Support), Support, Order.swigValue());
  }

  public int Add(TopoDS_Face Support, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_4(swigCPtr, this, TopoDS_Face.getCPtr(Support), Support, Order.swigValue());
  }

  public int Add(double[] Point) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_5(swigCPtr, this, Point);
  }

  public int Add(double U, double V, TopoDS_Face Support, GeomAbs_Shape Order) {
    return OccJavaJNI.BRepFill_Filling_Add__SWIG_6(swigCPtr, this, U, V, TopoDS_Face.getCPtr(Support), Support, Order.swigValue());
  }

  public void Build() {
    OccJavaJNI.BRepFill_Filling_Build(swigCPtr, this);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepFill_Filling_IsDone(swigCPtr, this);
}

  public TopoDS_Face Face() {
    return new TopoDS_Face(OccJavaJNI.BRepFill_Filling_Face(swigCPtr, this), true);
  }

  public double G0Error() {
    return OccJavaJNI.BRepFill_Filling_G0Error__SWIG_0(swigCPtr, this);
  }

  public double G1Error() {
    return OccJavaJNI.BRepFill_Filling_G1Error__SWIG_0(swigCPtr, this);
  }

  public double G2Error() {
    return OccJavaJNI.BRepFill_Filling_G2Error__SWIG_0(swigCPtr, this);
  }

  public double G0Error(int Index) {
    return OccJavaJNI.BRepFill_Filling_G0Error__SWIG_1(swigCPtr, this, Index);
  }

  public double G1Error(int Index) {
    return OccJavaJNI.BRepFill_Filling_G1Error__SWIG_1(swigCPtr, this, Index);
  }

  public double G2Error(int Index) {
    return OccJavaJNI.BRepFill_Filling_G2Error__SWIG_1(swigCPtr, this, Index);
  }

}
