/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_FindContigousEdges {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepOffsetAPI_FindContigousEdges(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_FindContigousEdges obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_FindContigousEdges(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepOffsetAPI_FindContigousEdges(double tolerance, boolean option) {
    this(OccJavaJNI.new_BRepOffsetAPI_FindContigousEdges__SWIG_0(tolerance, option), true);
  }

  public BRepOffsetAPI_FindContigousEdges(double tolerance) {
    this(OccJavaJNI.new_BRepOffsetAPI_FindContigousEdges__SWIG_1(tolerance), true);
  }

  public BRepOffsetAPI_FindContigousEdges() {
    this(OccJavaJNI.new_BRepOffsetAPI_FindContigousEdges__SWIG_2(), true);
  }

  public void Init(double tolerance, boolean option) {
    OccJavaJNI.BRepOffsetAPI_FindContigousEdges_Init(swigCPtr, this, tolerance, option);
  }

  public void Add(TopoDS_Shape shape) {
    OccJavaJNI.BRepOffsetAPI_FindContigousEdges_Add(swigCPtr, this, TopoDS_Shape.getCPtr(shape), shape);
  }

  public void Perform() {
    OccJavaJNI.BRepOffsetAPI_FindContigousEdges_Perform(swigCPtr, this);
  }

  public int NbContigousEdges() {
    return OccJavaJNI.BRepOffsetAPI_FindContigousEdges_NbContigousEdges(swigCPtr, this);
  }

  public TopoDS_Edge ContigousEdge(int index) {
    return new TopoDS_Edge(OccJavaJNI.BRepOffsetAPI_FindContigousEdges_ContigousEdge(swigCPtr, this, index), false);
  }

  public TopoDS_Shape[] ContigousEdgeCouple(int index) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_FindContigousEdges_ContigousEdgeCouple(swigCPtr, this, index));
}

  public TopoDS_Edge SectionToBoundary(TopoDS_Edge section) {
    return new TopoDS_Edge(OccJavaJNI.BRepOffsetAPI_FindContigousEdges_SectionToBoundary(swigCPtr, this, TopoDS_Edge.getCPtr(section), section), false);
  }

  public int NbDegeneratedShapes() {
    return OccJavaJNI.BRepOffsetAPI_FindContigousEdges_NbDegeneratedShapes(swigCPtr, this);
  }

  public TopoDS_Shape DegeneratedShape(int index) {
    long cPtr = OccJavaJNI.BRepOffsetAPI_FindContigousEdges_DegeneratedShape(swigCPtr, this, index);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public boolean IsDegenerated(TopoDS_Shape shape) {
	return OccJavaJNI.BRepOffsetAPI_FindContigousEdges_IsDegenerated(swigCPtr, this, TopoDS_Shape.getCPtr(shape), shape);
}

  public boolean IsModified(TopoDS_Shape shape) {
	return OccJavaJNI.BRepOffsetAPI_FindContigousEdges_IsModified(swigCPtr, this, TopoDS_Shape.getCPtr(shape), shape);
}

  public TopoDS_Shape Modified(TopoDS_Shape shape) {
    long cPtr = OccJavaJNI.BRepOffsetAPI_FindContigousEdges_Modified(swigCPtr, this, TopoDS_Shape.getCPtr(shape), shape);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public void Dump() {
    OccJavaJNI.BRepOffsetAPI_FindContigousEdges_Dump(swigCPtr, this);
  }

}
