/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TopoDS_Face Face(TopoDS_Edge Edge1, TopoDS_Edge Edge2) {
    return new TopoDS_Face(OccJavaJNI.BRepFill_Face(swigCPtr, this, TopoDS_Edge.getCPtr(Edge1), Edge1, TopoDS_Edge.getCPtr(Edge2), Edge2), true);
  }

  public TopoDS_Shell Shell(TopoDS_Wire Wire1, TopoDS_Wire Wire2) {
    return new TopoDS_Shell(OccJavaJNI.BRepFill_Shell(swigCPtr, this, TopoDS_Wire.getCPtr(Wire1), Wire1, TopoDS_Wire.getCPtr(Wire2), Wire2), true);
  }

  public void Axe(TopoDS_Shape Spine, TopoDS_Wire Profile, double[] AxeProf, boolean ProfOnSpine, double Tol) {
    OccJavaJNI.BRepFill_Axe(swigCPtr, this, TopoDS_Shape.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, ProfOnSpine, Tol);
  }

  public void ComputeACR(TopoDS_Wire wire, double[] ACR) {
    OccJavaJNI.BRepFill_ComputeACR(swigCPtr, this, TopoDS_Wire.getCPtr(wire), wire, ACR);
  }

  public TopoDS_Wire InsertACR(TopoDS_Wire wire, double[] ACRcuts, double prec) {
    return new TopoDS_Wire(OccJavaJNI.BRepFill_InsertACR(swigCPtr, this, TopoDS_Wire.getCPtr(wire), wire, ACRcuts, prec), true);
  }

  public BRepFill() {
    this(OccJavaJNI.new_BRepFill(), true);
  }

}
