/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_OffsetWire {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_OffsetWire(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_OffsetWire obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_OffsetWire(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_OffsetWire() {
    this(OccJavaJNI.new_BRepFill_OffsetWire__SWIG_0(), true);
  }

  public BRepFill_OffsetWire(TopoDS_Face Spine, GeomAbs_JoinType Join) {
    this(OccJavaJNI.new_BRepFill_OffsetWire__SWIG_1(TopoDS_Face.getCPtr(Spine), Spine, Join.swigValue()), true);
  }

  public BRepFill_OffsetWire(TopoDS_Face Spine) {
    this(OccJavaJNI.new_BRepFill_OffsetWire__SWIG_2(TopoDS_Face.getCPtr(Spine), Spine), true);
  }

  public void Init(TopoDS_Face Spine, GeomAbs_JoinType Join) {
    OccJavaJNI.BRepFill_OffsetWire_Init__SWIG_0(swigCPtr, this, TopoDS_Face.getCPtr(Spine), Spine, Join.swigValue());
  }

  public void Init(TopoDS_Face Spine) {
    OccJavaJNI.BRepFill_OffsetWire_Init__SWIG_1(swigCPtr, this, TopoDS_Face.getCPtr(Spine), Spine);
  }

  public void Perform(double Offset, double Alt) {
    OccJavaJNI.BRepFill_OffsetWire_Perform__SWIG_0(swigCPtr, this, Offset, Alt);
  }

  public void Perform(double Offset) {
    OccJavaJNI.BRepFill_OffsetWire_Perform__SWIG_1(swigCPtr, this, Offset);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepFill_OffsetWire_IsDone(swigCPtr, this);
}

  public TopoDS_Face Spine() {
    return new TopoDS_Face(OccJavaJNI.BRepFill_OffsetWire_Spine(swigCPtr, this), false);
  }

  public TopoDS_Shape Shape() {
    long cPtr = OccJavaJNI.BRepFill_OffsetWire_Shape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape[] GeneratedShapes(TopoDS_Shape SpineShape) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFill_OffsetWire_GeneratedShapes(swigCPtr, this, TopoDS_Shape.getCPtr(SpineShape), SpineShape));
}

  public GeomAbs_JoinType JoinType() {
    return GeomAbs_JoinType.swigToEnum(OccJavaJNI.BRepFill_OffsetWire_JoinType(swigCPtr, this));
  }

}
