/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFeat_Gluer extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepFeat_Gluer(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepFeat_Gluer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFeat_Gluer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFeat_Gluer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void Build() {
    OccJavaJNI.BRepFeat_Gluer_Build(swigCPtr, this);
  }

  public boolean IsDeleted(TopoDS_Shape F) {
	return OccJavaJNI.BRepFeat_Gluer_IsDeleted(swigCPtr, this, TopoDS_Shape.getCPtr(F), F);
}

  public TopoDS_Shape[] Modified(TopoDS_Shape F) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFeat_Gluer_Modified(swigCPtr, this, TopoDS_Shape.getCPtr(F), F));
}

}
