/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_OffsetAncestors {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_OffsetAncestors(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_OffsetAncestors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_OffsetAncestors(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_OffsetAncestors() {
    this(OccJavaJNI.new_BRepFill_OffsetAncestors__SWIG_0(), true);
  }

  public BRepFill_OffsetAncestors(BRepFill_OffsetWire Paral) {
    this(OccJavaJNI.new_BRepFill_OffsetAncestors__SWIG_1(BRepFill_OffsetWire.getCPtr(Paral), Paral), true);
  }

  public void Perform(BRepFill_OffsetWire Paral) {
    OccJavaJNI.BRepFill_OffsetAncestors_Perform(swigCPtr, this, BRepFill_OffsetWire.getCPtr(Paral), Paral);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepFill_OffsetAncestors_IsDone(swigCPtr, this);
}

  public boolean HasAncestor(TopoDS_Edge S1) {
	return OccJavaJNI.BRepFill_OffsetAncestors_HasAncestor(swigCPtr, this, TopoDS_Edge.getCPtr(S1), S1);
}

  public TopoDS_Shape Ancestor(TopoDS_Edge S1) {
    long cPtr = OccJavaJNI.BRepFill_OffsetAncestors_Ancestor(swigCPtr, this, TopoDS_Edge.getCPtr(S1), S1);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

}
