/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepBuilderAPI_MakeShell extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepBuilderAPI_MakeShell(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepBuilderAPI_MakeShell_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepBuilderAPI_MakeShell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepBuilderAPI_MakeShell(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepBuilderAPI_MakeShell() {
    this(OccJavaJNI.new_BRepBuilderAPI_MakeShell__SWIG_0(), true);
  }

  public BRepBuilderAPI_MakeShell(Geom_Surface S, boolean Segment) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakeShell__SWIG_1(Geom_Surface.getCPtr(S), S, Segment), true);
  }

  public BRepBuilderAPI_MakeShell(Geom_Surface S) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakeShell__SWIG_2(Geom_Surface.getCPtr(S), S), true);
  }

  public BRepBuilderAPI_MakeShell(Geom_Surface S, double UMin, double UMax, double VMin, double VMax, boolean Segment) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakeShell__SWIG_3(Geom_Surface.getCPtr(S), S, UMin, UMax, VMin, VMax, Segment), true);
  }

  public BRepBuilderAPI_MakeShell(Geom_Surface S, double UMin, double UMax, double VMin, double VMax) {
    this(OccJavaJNI.new_BRepBuilderAPI_MakeShell__SWIG_4(Geom_Surface.getCPtr(S), S, UMin, UMax, VMin, VMax), true);
  }

  public void Init(Geom_Surface S, double UMin, double UMax, double VMin, double VMax, boolean Segment) {
    OccJavaJNI.BRepBuilderAPI_MakeShell_Init__SWIG_0(swigCPtr, this, Geom_Surface.getCPtr(S), S, UMin, UMax, VMin, VMax, Segment);
  }

  public void Init(Geom_Surface S, double UMin, double UMax, double VMin, double VMax) {
    OccJavaJNI.BRepBuilderAPI_MakeShell_Init__SWIG_1(swigCPtr, this, Geom_Surface.getCPtr(S), S, UMin, UMax, VMin, VMax);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepBuilderAPI_MakeShell_IsDone(swigCPtr, this);
}

  public TopoDS_Shell Shell() {
    return new TopoDS_Shell(OccJavaJNI.BRepBuilderAPI_MakeShell_Shell(swigCPtr, this), false);
  }

}
