/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_Evolved {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_Evolved(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_Evolved obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_Evolved(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_Evolved() {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_0(), true);
  }

  public BRepFill_Evolved(TopoDS_Wire Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join, boolean Solid) {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_1(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue(), Solid), true);
  }

  public BRepFill_Evolved(TopoDS_Wire Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join) {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_2(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue()), true);
  }

  public BRepFill_Evolved(TopoDS_Wire Spine, TopoDS_Wire Profile, double[] AxeProf) {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_3(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf), true);
  }

  public BRepFill_Evolved(TopoDS_Face Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join, boolean Solid) {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_4(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue(), Solid), true);
  }

  public BRepFill_Evolved(TopoDS_Face Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join) {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_5(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue()), true);
  }

  public BRepFill_Evolved(TopoDS_Face Spine, TopoDS_Wire Profile, double[] AxeProf) {
    this(OccJavaJNI.new_BRepFill_Evolved__SWIG_6(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf), true);
  }

  public void Perform(TopoDS_Wire Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join, boolean Solid) {
    OccJavaJNI.BRepFill_Evolved_Perform__SWIG_0(swigCPtr, this, TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue(), Solid);
  }

  public void Perform(TopoDS_Wire Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join) {
    OccJavaJNI.BRepFill_Evolved_Perform__SWIG_1(swigCPtr, this, TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue());
  }

  public void Perform(TopoDS_Wire Spine, TopoDS_Wire Profile, double[] AxeProf) {
    OccJavaJNI.BRepFill_Evolved_Perform__SWIG_2(swigCPtr, this, TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf);
  }

  public void Perform(TopoDS_Face Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join, boolean Solid) {
    OccJavaJNI.BRepFill_Evolved_Perform__SWIG_3(swigCPtr, this, TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue(), Solid);
  }

  public void Perform(TopoDS_Face Spine, TopoDS_Wire Profile, double[] AxeProf, GeomAbs_JoinType Join) {
    OccJavaJNI.BRepFill_Evolved_Perform__SWIG_4(swigCPtr, this, TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf, Join.swigValue());
  }

  public void Perform(TopoDS_Face Spine, TopoDS_Wire Profile, double[] AxeProf) {
    OccJavaJNI.BRepFill_Evolved_Perform__SWIG_5(swigCPtr, this, TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profile), Profile, AxeProf);
  }

  public boolean IsDone() {
	return OccJavaJNI.BRepFill_Evolved_IsDone(swigCPtr, this);
}

  public TopoDS_Shape Shape() {
    long cPtr = OccJavaJNI.BRepFill_Evolved_Shape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape[] GeneratedShapes(TopoDS_Shape SpineShape, TopoDS_Shape ProfShape) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepFill_Evolved_GeneratedShapes(swigCPtr, this, TopoDS_Shape.getCPtr(SpineShape), SpineShape, TopoDS_Shape.getCPtr(ProfShape), ProfShape));
}

  public GeomAbs_JoinType JoinType() {
    return GeomAbs_JoinType.swigToEnum(OccJavaJNI.BRepFill_Evolved_JoinType(swigCPtr, this));
  }

  public TopoDS_Shape Top() {
    long cPtr = OccJavaJNI.BRepFill_Evolved_Top(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape Bottom() {
    long cPtr = OccJavaJNI.BRepFill_Evolved_Bottom(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

}
