/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepFill_Section {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepFill_Section(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepFill_Section obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepFill_Section(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BRepFill_Section() {
    this(OccJavaJNI.new_BRepFill_Section__SWIG_0(), true);
  }

  public BRepFill_Section(TopoDS_Shape Profile, TopoDS_Vertex V, boolean WithContact, boolean WithCorrection) {
    this(OccJavaJNI.new_BRepFill_Section__SWIG_1(TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(V), V, WithContact, WithCorrection), true);
  }

  public void Set(boolean IsLaw) {
    OccJavaJNI.BRepFill_Section_Set(swigCPtr, this, IsLaw);
  }

  public TopoDS_Wire Wire() {
    return new TopoDS_Wire(OccJavaJNI.BRepFill_Section_Wire(swigCPtr, this), false);
  }

  public TopoDS_Vertex Vertex() {
    return new TopoDS_Vertex(OccJavaJNI.BRepFill_Section_Vertex(swigCPtr, this), false);
  }

  public boolean IsLaw() {
	return OccJavaJNI.BRepFill_Section_IsLaw(swigCPtr, this);
}

  public boolean WithContact() {
	return OccJavaJNI.BRepFill_Section_WithContact(swigCPtr, this);
}

  public boolean WithCorrection() {
	return OccJavaJNI.BRepFill_Section_WithCorrection(swigCPtr, this);
}

}
