/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepPrimAPI_MakeWedge extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepPrimAPI_MakeWedge(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepPrimAPI_MakeWedge_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepPrimAPI_MakeWedge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepPrimAPI_MakeWedge(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepPrimAPI_MakeWedge(double dx, double dy, double dz, double ltx) {
    this(OccJavaJNI.new_BRepPrimAPI_MakeWedge__SWIG_0(dx, dy, dz, ltx), true);
  }

  public BRepPrimAPI_MakeWedge(double[] Axes, double dx, double dy, double dz, double ltx) {
    this(OccJavaJNI.new_BRepPrimAPI_MakeWedge__SWIG_1(Axes, dx, dy, dz, ltx), true);
  }

  public BRepPrimAPI_MakeWedge(double dx, double dy, double dz, double xmin, double zmin, double xmax, double zmax) {
    this(OccJavaJNI.new_BRepPrimAPI_MakeWedge__SWIG_2(dx, dy, dz, xmin, zmin, xmax, zmax), true);
  }

  public BRepPrimAPI_MakeWedge(double[] Axes, double dx, double dy, double dz, double xmin, double zmin, double xmax, double zmax) {
    this(OccJavaJNI.new_BRepPrimAPI_MakeWedge__SWIG_3(Axes, dx, dy, dz, xmin, zmin, xmax, zmax), true);
  }

  public void Build() {
    OccJavaJNI.BRepPrimAPI_MakeWedge_Build(swigCPtr, this);
  }

  public TopoDS_Shell Shell() {
    return new TopoDS_Shell(OccJavaJNI.BRepPrimAPI_MakeWedge_Shell(swigCPtr, this), false);
  }

  public TopoDS_Solid Solid() {
    return new TopoDS_Solid(OccJavaJNI.BRepPrimAPI_MakeWedge_Solid(swigCPtr, this), false);
  }

}
