/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_MakeEvolved extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  public BRepOffsetAPI_MakeEvolved(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_MakeEvolved_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepOffsetAPI_MakeEvolved obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_MakeEvolved(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_MakeEvolved() {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_0(), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Wire Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf, boolean Solid, boolean ProfOnSpine, double Tol) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_1(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf, Solid, ProfOnSpine, Tol), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Wire Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf, boolean Solid, boolean ProfOnSpine) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_2(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf, Solid, ProfOnSpine), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Wire Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf, boolean Solid) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_3(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf, Solid), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Wire Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_4(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Wire Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_5(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue()), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Wire Spine, TopoDS_Wire Profil) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_6(TopoDS_Wire.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Face Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf, boolean Solid, boolean ProfOnSpine, double Tol) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_7(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf, Solid, ProfOnSpine, Tol), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Face Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf, boolean Solid, boolean ProfOnSpine) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_8(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf, Solid, ProfOnSpine), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Face Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf, boolean Solid) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_9(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf, Solid), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Face Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join, boolean AxeProf) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_10(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue(), AxeProf), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Face Spine, TopoDS_Wire Profil, GeomAbs_JoinType Join) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_11(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil, Join.swigValue()), true);
  }

  public BRepOffsetAPI_MakeEvolved(TopoDS_Face Spine, TopoDS_Wire Profil) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakeEvolved__SWIG_12(TopoDS_Face.getCPtr(Spine), Spine, TopoDS_Wire.getCPtr(Profil), Profil), true);
  }

  public void Build() {
    OccJavaJNI.BRepOffsetAPI_MakeEvolved_Build(swigCPtr, this);
  }

  public TopoDS_Shape[] GeneratedShapes(TopoDS_Shape SpineShape, TopoDS_Shape ProfShape) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_MakeEvolved_GeneratedShapes(swigCPtr, this, TopoDS_Shape.getCPtr(SpineShape), SpineShape, TopoDS_Shape.getCPtr(ProfShape), ProfShape));
}

  public TopoDS_Shape Top() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_MakeEvolved_Top(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape Bottom() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_MakeEvolved_Bottom(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

}
