/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepBuilderAPI {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BRepBuilderAPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BRepBuilderAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepBuilderAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Plane(Geom_Plane P) {
    OccJavaJNI.BRepBuilderAPI_Plane__SWIG_0(swigCPtr, this, Geom_Plane.getCPtr(P), P);
  }

  public Geom_Plane Plane() {
    return new Geom_Plane(OccJavaJNI.BRepBuilderAPI_Plane__SWIG_1(swigCPtr, this), false);
  }

  public void Precision(double P) {
    OccJavaJNI.BRepBuilderAPI_Precision__SWIG_0(swigCPtr, this, P);
  }

  public double Precision() {
    return OccJavaJNI.BRepBuilderAPI_Precision__SWIG_1(swigCPtr, this);
  }

  public BRepBuilderAPI() {
    this(OccJavaJNI.new_BRepBuilderAPI(), true);
  }

}
