/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GC_MakeArcOfCircle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GC_MakeArcOfCircle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GC_MakeArcOfCircle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GC_MakeArcOfCircle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GC_MakeArcOfCircle(double[] P1, double[] P2, double[] P3) {
    this(OccJavaJNI.new_GC_MakeArcOfCircle__SWIG_0(P1, P2, P3), true);
  }

  public GC_MakeArcOfCircle(GP_Circ Circ, double[] P1, double[] P2, boolean Sense) {
    this(OccJavaJNI.new_GC_MakeArcOfCircle__SWIG_1(GP_Circ.getCPtr(Circ), Circ, P1, P2, Sense), true);
  }

  public Geom_TrimmedCurve Value() {
    return new Geom_TrimmedCurve(OccJavaJNI.GC_MakeArcOfCircle_Value(swigCPtr, this), false);
  }

}
