/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Axis1Placement extends Geom_AxisPlacement {
  private long swigCPtr;

  public Geom_Axis1Placement(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Axis1Placement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Axis1Placement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Axis1Placement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_Axis1Placement(double[] A1) {
    this(OccJavaJNI.new_Geom_Axis1Placement__SWIG_0(A1), true);
  }

  public Geom_Axis1Placement(double[] P, double[] V) {
    this(OccJavaJNI.new_Geom_Axis1Placement__SWIG_1(P, V), true);
  }

  public double[] Ax1() {
	return OccJavaJNI.Geom_Axis1Placement_Ax1(swigCPtr, this);
}

  public void Reverse() {
    OccJavaJNI.Geom_Axis1Placement_Reverse(swigCPtr, this);
  }

  public void SetDirection(double[] V) {
    OccJavaJNI.Geom_Axis1Placement_SetDirection(swigCPtr, this, V);
  }

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_Axis1Placement_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
