/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Axis2Placement extends Geom_AxisPlacement {
  private long swigCPtr;

  public Geom_Axis2Placement(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Axis2Placement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Axis2Placement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Axis2Placement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_Axis2Placement(double[] A2) {
    this(OccJavaJNI.new_Geom_Axis2Placement__SWIG_0(A2), true);
  }

  public Geom_Axis2Placement(double[] P, double[] N, double[] Vx) {
    this(OccJavaJNI.new_Geom_Axis2Placement__SWIG_1(P, N, Vx), true);
  }

  public void SetAx2(double[] A2) {
    OccJavaJNI.Geom_Axis2Placement_SetAx2(swigCPtr, this, A2);
  }

  public void SetDirection(double[] V) {
    OccJavaJNI.Geom_Axis2Placement_SetDirection(swigCPtr, this, V);
  }

  public void SetXDirection(double[] Vx) {
    OccJavaJNI.Geom_Axis2Placement_SetXDirection(swigCPtr, this, Vx);
  }

  public void SetYDirection(double[] Vy) {
    OccJavaJNI.Geom_Axis2Placement_SetYDirection(swigCPtr, this, Vy);
  }

  public double[] Ax2() {
	return OccJavaJNI.Geom_Axis2Placement_Ax2(swigCPtr, this);
}

  public double[] XDirection() {
	return OccJavaJNI.Geom_Axis2Placement_XDirection(swigCPtr, this);
}

  public double[] YDirection() {
	return OccJavaJNI.Geom_Axis2Placement_YDirection(swigCPtr, this);
}

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_Axis2Placement_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
