/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomFill_BezierCurves {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomFill_BezierCurves(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomFill_BezierCurves obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomFill_BezierCurves(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomFill_BezierCurves() {
    this(OccJavaJNI.new_GeomFill_BezierCurves__SWIG_0(), true);
  }

  public GeomFill_BezierCurves(Geom_BezierCurve C1, Geom_BezierCurve C2, Geom_BezierCurve C3, Geom_BezierCurve C4, GeomFill_FillingStyle Type) {
    this(OccJavaJNI.new_GeomFill_BezierCurves__SWIG_1(Geom_BezierCurve.getCPtr(C1), C1, Geom_BezierCurve.getCPtr(C2), C2, Geom_BezierCurve.getCPtr(C3), C3, Geom_BezierCurve.getCPtr(C4), C4, Type.swigValue()), true);
  }

  public GeomFill_BezierCurves(Geom_BezierCurve C1, Geom_BezierCurve C2, Geom_BezierCurve C3, GeomFill_FillingStyle Type) {
    this(OccJavaJNI.new_GeomFill_BezierCurves__SWIG_2(Geom_BezierCurve.getCPtr(C1), C1, Geom_BezierCurve.getCPtr(C2), C2, Geom_BezierCurve.getCPtr(C3), C3, Type.swigValue()), true);
  }

  public GeomFill_BezierCurves(Geom_BezierCurve C1, Geom_BezierCurve C2, GeomFill_FillingStyle Type) {
    this(OccJavaJNI.new_GeomFill_BezierCurves__SWIG_3(Geom_BezierCurve.getCPtr(C1), C1, Geom_BezierCurve.getCPtr(C2), C2, Type.swigValue()), true);
  }

  public void Init(Geom_BezierCurve C1, Geom_BezierCurve C2, Geom_BezierCurve C3, Geom_BezierCurve C4, GeomFill_FillingStyle Type) {
    OccJavaJNI.GeomFill_BezierCurves_Init__SWIG_0(swigCPtr, this, Geom_BezierCurve.getCPtr(C1), C1, Geom_BezierCurve.getCPtr(C2), C2, Geom_BezierCurve.getCPtr(C3), C3, Geom_BezierCurve.getCPtr(C4), C4, Type.swigValue());
  }

  public void Init(Geom_BezierCurve C1, Geom_BezierCurve C2, Geom_BezierCurve C3, GeomFill_FillingStyle Type) {
    OccJavaJNI.GeomFill_BezierCurves_Init__SWIG_1(swigCPtr, this, Geom_BezierCurve.getCPtr(C1), C1, Geom_BezierCurve.getCPtr(C2), C2, Geom_BezierCurve.getCPtr(C3), C3, Type.swigValue());
  }

  public void Init(Geom_BezierCurve C1, Geom_BezierCurve C2, GeomFill_FillingStyle Type) {
    OccJavaJNI.GeomFill_BezierCurves_Init__SWIG_2(swigCPtr, this, Geom_BezierCurve.getCPtr(C1), C1, Geom_BezierCurve.getCPtr(C2), C2, Type.swigValue());
  }

  public Geom_BezierSurface Surface() {
    return new Geom_BezierSurface(OccJavaJNI.GeomFill_BezierCurves_Surface(swigCPtr, this), false);
  }

}
