/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_TrimmedCurve extends Geom_BoundedCurve {
  private long swigCPtr;

  public Geom_TrimmedCurve(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_TrimmedCurve_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_TrimmedCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_TrimmedCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_TrimmedCurve(Geom_Curve C, double U1, double U2, boolean Sense) {
    this(OccJavaJNI.new_Geom_TrimmedCurve__SWIG_0(Geom_Curve.getCPtr(C), C, U1, U2, Sense), true);
  }

  public Geom_TrimmedCurve(Geom_Curve C, double U1, double U2) {
    this(OccJavaJNI.new_Geom_TrimmedCurve__SWIG_1(Geom_Curve.getCPtr(C), C, U1, U2), true);
  }

  public void Reverse() {
    OccJavaJNI.Geom_TrimmedCurve_Reverse(swigCPtr, this);
  }

  public double ReversedParameter(double U) {
    return OccJavaJNI.Geom_TrimmedCurve_ReversedParameter(swigCPtr, this, U);
  }

  public void SetTrim(double U1, double U2, boolean Sense) {
    OccJavaJNI.Geom_TrimmedCurve_SetTrim__SWIG_0(swigCPtr, this, U1, U2, Sense);
  }

  public void SetTrim(double U1, double U2) {
    OccJavaJNI.Geom_TrimmedCurve_SetTrim__SWIG_1(swigCPtr, this, U1, U2);
  }

  public Geom_Curve BasisCurve() {
    return new Geom_Curve(OccJavaJNI.Geom_TrimmedCurve_BasisCurve(swigCPtr, this), true);
  }

  public GeomAbs_Shape Continuity() {
    return GeomAbs_Shape.swigToEnum(OccJavaJNI.Geom_TrimmedCurve_Continuity(swigCPtr, this));
  }

  public boolean IsCN(int N) {
	return OccJavaJNI.Geom_TrimmedCurve_IsCN(swigCPtr, this, N);
}

  public double[] EndPoint() {
	return OccJavaJNI.Geom_TrimmedCurve_EndPoint(swigCPtr, this);
}

  public double FirstParameter() {
    return OccJavaJNI.Geom_TrimmedCurve_FirstParameter(swigCPtr, this);
  }

  public boolean IsClosed() {
	return OccJavaJNI.Geom_TrimmedCurve_IsClosed(swigCPtr, this);
}

  public boolean IsPeriodic() {
	return OccJavaJNI.Geom_TrimmedCurve_IsPeriodic(swigCPtr, this);
}

  public double Period() {
    return OccJavaJNI.Geom_TrimmedCurve_Period(swigCPtr, this);
  }

  public double LastParameter() {
    return OccJavaJNI.Geom_TrimmedCurve_LastParameter(swigCPtr, this);
  }

  public double[] StartPoint() {
	return OccJavaJNI.Geom_TrimmedCurve_StartPoint(swigCPtr, this);
}

  public void D0(double U, double[] P) {
    OccJavaJNI.Geom_TrimmedCurve_D0(swigCPtr, this, U, P);
  }

  public void D1(double U, double[] P, double[] V1) {
    OccJavaJNI.Geom_TrimmedCurve_D1(swigCPtr, this, U, P, V1);
  }

  public void D2(double U, double[] P, double[] V1, double[] V2) {
    OccJavaJNI.Geom_TrimmedCurve_D2(swigCPtr, this, U, P, V1, V2);
  }

  public void D3(double U, double[] P, double[] V1, double[] V2, double[] V3) {
    OccJavaJNI.Geom_TrimmedCurve_D3(swigCPtr, this, U, P, V1, V2, V3);
  }

  public double[] DN(double U, int N) {
	return OccJavaJNI.Geom_TrimmedCurve_DN(swigCPtr, this, U, N);
}

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_TrimmedCurve_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

  public double TransformedParameter(double U, GP_Trsf T) {
    return OccJavaJNI.Geom_TrimmedCurve_TransformedParameter(swigCPtr, this, U, GP_Trsf.getCPtr(T), T);
  }

  public double ParametricTransformation(GP_Trsf T) {
    return OccJavaJNI.Geom_TrimmedCurve_ParametricTransformation(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
