/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomConvert_BSplineSurfaceToBezierSurface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomConvert_BSplineSurfaceToBezierSurface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomConvert_BSplineSurfaceToBezierSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomConvert_BSplineSurfaceToBezierSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomConvert_BSplineSurfaceToBezierSurface(Geom_BSplineSurface BasisSurface) {
    this(OccJavaJNI.new_GeomConvert_BSplineSurfaceToBezierSurface__SWIG_0(Geom_BSplineSurface.getCPtr(BasisSurface), BasisSurface), true);
  }

  public GeomConvert_BSplineSurfaceToBezierSurface(Geom_BSplineSurface BasisSurface, double U1, double U2, double V1, double V2, double ParametricTolerance) {
    this(OccJavaJNI.new_GeomConvert_BSplineSurfaceToBezierSurface__SWIG_1(Geom_BSplineSurface.getCPtr(BasisSurface), BasisSurface, U1, U2, V1, V2, ParametricTolerance), true);
  }

  public Geom_BezierSurface Patch(int UIndex, int VIndex) {
    return new Geom_BezierSurface(OccJavaJNI.GeomConvert_BSplineSurfaceToBezierSurface_Patch(swigCPtr, this, UIndex, VIndex), true);
  }

  public void UKnots(double[] TKnots) {
    OccJavaJNI.GeomConvert_BSplineSurfaceToBezierSurface_UKnots(swigCPtr, this, TKnots);
  }

  public void VKnots(double[] TKnots) {
    OccJavaJNI.GeomConvert_BSplineSurfaceToBezierSurface_VKnots(swigCPtr, this, TKnots);
  }

  public int NbUPatches() {
    return OccJavaJNI.GeomConvert_BSplineSurfaceToBezierSurface_NbUPatches(swigCPtr, this);
  }

  public int NbVPatches() {
    return OccJavaJNI.GeomConvert_BSplineSurfaceToBezierSurface_NbVPatches(swigCPtr, this);
  }

}
