/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomConvert_BSplineCurveKnotSplitting {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomConvert_BSplineCurveKnotSplitting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomConvert_BSplineCurveKnotSplitting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomConvert_BSplineCurveKnotSplitting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomConvert_BSplineCurveKnotSplitting(Geom_BSplineCurve BasisCurve, int ContinuityRange) {
    this(OccJavaJNI.new_GeomConvert_BSplineCurveKnotSplitting(Geom_BSplineCurve.getCPtr(BasisCurve), BasisCurve, ContinuityRange), true);
  }

  public int NbSplits() {
    return OccJavaJNI.GeomConvert_BSplineCurveKnotSplitting_NbSplits(swigCPtr, this);
  }

  public void Splitting(int[] SplitValues) {
    OccJavaJNI.GeomConvert_BSplineCurveKnotSplitting_Splitting(swigCPtr, this, SplitValues);
  }

  public int SplitValue(int Index) {
    return OccJavaJNI.GeomConvert_BSplineCurveKnotSplitting_SplitValue(swigCPtr, this, Index);
  }

}
