/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomConvert_ApproxCurve {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomConvert_ApproxCurve(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomConvert_ApproxCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomConvert_ApproxCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomConvert_ApproxCurve(Geom_Curve Curve, double Tol3d, GeomAbs_Shape Order, int MaxSegments, int MaxDegree) {
    this(OccJavaJNI.new_GeomConvert_ApproxCurve(Geom_Curve.getCPtr(Curve), Curve, Tol3d, Order.swigValue(), MaxSegments, MaxDegree), true);
  }

  public Geom_BSplineCurve Curve() {
    return new Geom_BSplineCurve(OccJavaJNI.GeomConvert_ApproxCurve_Curve(swigCPtr, this), true);
  }

  public boolean IsDone() {
	return OccJavaJNI.GeomConvert_ApproxCurve_IsDone(swigCPtr, this);
}

  public boolean HasResult() {
	return OccJavaJNI.GeomConvert_ApproxCurve_HasResult(swigCPtr, this);
}

  public double MaxError() {
    return OccJavaJNI.GeomConvert_ApproxCurve_MaxError(swigCPtr, this);
  }

}
