/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_VectorWithMagnitude extends Geom_Vector {
  private long swigCPtr;

  public Geom_VectorWithMagnitude(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_VectorWithMagnitude_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_VectorWithMagnitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_VectorWithMagnitude(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_VectorWithMagnitude(double X, double Y, double Z) {
    this(OccJavaJNI.new_Geom_VectorWithMagnitude__SWIG_0(X, Y, Z), true);
  }

  public Geom_VectorWithMagnitude(double[] V) {
    this(OccJavaJNI.new_Geom_VectorWithMagnitude__SWIG_1(V), true);
  }

  public Geom_VectorWithMagnitude(double[] P1, double[] P2) {
    this(OccJavaJNI.new_Geom_VectorWithMagnitude__SWIG_2(P1, P2), true);
  }

  public void SetCoord(double X, double Y, double Z) {
    OccJavaJNI.Geom_VectorWithMagnitude_SetCoord(swigCPtr, this, X, Y, Z);
  }

  public void SetVec(double[] V) {
    OccJavaJNI.Geom_VectorWithMagnitude_SetVec(swigCPtr, this, V);
  }

  public void SetX(double X) {
    OccJavaJNI.Geom_VectorWithMagnitude_SetX(swigCPtr, this, X);
  }

  public void SetY(double Y) {
    OccJavaJNI.Geom_VectorWithMagnitude_SetY(swigCPtr, this, Y);
  }

  public void SetZ(double Z) {
    OccJavaJNI.Geom_VectorWithMagnitude_SetZ(swigCPtr, this, Z);
  }

  public double Magnitude() {
    return OccJavaJNI.Geom_VectorWithMagnitude_Magnitude(swigCPtr, this);
  }

  public double SquareMagnitude() {
    return OccJavaJNI.Geom_VectorWithMagnitude_SquareMagnitude(swigCPtr, this);
  }

  public void Add(Geom_Vector Other) {
    OccJavaJNI.Geom_VectorWithMagnitude_Add(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public void Cross(Geom_Vector Other) {
    OccJavaJNI.Geom_VectorWithMagnitude_Cross(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public void CrossCross(Geom_Vector V1, Geom_Vector V2) {
    OccJavaJNI.Geom_VectorWithMagnitude_CrossCross(swigCPtr, this, Geom_Vector.getCPtr(V1), V1, Geom_Vector.getCPtr(V2), V2);
  }

  public void Divide(double Scalar) {
    OccJavaJNI.Geom_VectorWithMagnitude_Divide(swigCPtr, this, Scalar);
  }

  public void Multiply(double Scalar) {
    OccJavaJNI.Geom_VectorWithMagnitude_Multiply(swigCPtr, this, Scalar);
  }

  public void Normalize() {
    OccJavaJNI.Geom_VectorWithMagnitude_Normalize(swigCPtr, this);
  }

  public void Subtract(Geom_Vector Other) {
    OccJavaJNI.Geom_VectorWithMagnitude_Subtract(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_VectorWithMagnitude_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
