/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_AxisPlacement extends Geom_Geometry {
  private long swigCPtr;

  public Geom_AxisPlacement(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_AxisPlacement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_AxisPlacement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_AxisPlacement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void SetAxis(double[] A1) {
    OccJavaJNI.Geom_AxisPlacement_SetAxis(swigCPtr, this, A1);
  }

  public void SetDirection(double[] V) {
    OccJavaJNI.Geom_AxisPlacement_SetDirection(swigCPtr, this, V);
  }

  public void SetLocation(double[] P) {
    OccJavaJNI.Geom_AxisPlacement_SetLocation(swigCPtr, this, P);
  }

  public double Angle(Geom_AxisPlacement Other) {
    return OccJavaJNI.Geom_AxisPlacement_Angle(swigCPtr, this, Geom_AxisPlacement.getCPtr(Other), Other);
  }

  public double[] Axis() {
	return OccJavaJNI.Geom_AxisPlacement_Axis(swigCPtr, this);
}

  public double[] Direction() {
	return OccJavaJNI.Geom_AxisPlacement_Direction(swigCPtr, this);
}

  public double[] Location() {
	return OccJavaJNI.Geom_AxisPlacement_Location(swigCPtr, this);
}

}
