/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomConvert_BSplineCurveToBezierCurve {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomConvert_BSplineCurveToBezierCurve(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomConvert_BSplineCurveToBezierCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomConvert_BSplineCurveToBezierCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomConvert_BSplineCurveToBezierCurve(Geom_BSplineCurve BasisCurve) {
    this(OccJavaJNI.new_GeomConvert_BSplineCurveToBezierCurve__SWIG_0(Geom_BSplineCurve.getCPtr(BasisCurve), BasisCurve), true);
  }

  public GeomConvert_BSplineCurveToBezierCurve(Geom_BSplineCurve BasisCurve, double U1, double U2, double ParametricTolerance) {
    this(OccJavaJNI.new_GeomConvert_BSplineCurveToBezierCurve__SWIG_1(Geom_BSplineCurve.getCPtr(BasisCurve), BasisCurve, U1, U2, ParametricTolerance), true);
  }

  public Geom_BezierCurve Arc(int Index) {
    return new Geom_BezierCurve(OccJavaJNI.GeomConvert_BSplineCurveToBezierCurve_Arc(swigCPtr, this, Index), true);
  }

  public void Knots(double[] TKnots) {
    OccJavaJNI.GeomConvert_BSplineCurveToBezierCurve_Knots(swigCPtr, this, TKnots);
  }

  public int NbArcs() {
    return OccJavaJNI.GeomConvert_BSplineCurveToBezierCurve_NbArcs(swigCPtr, this);
  }

}
