/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomConvert_BSplineSurfaceKnotSplitting {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomConvert_BSplineSurfaceKnotSplitting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomConvert_BSplineSurfaceKnotSplitting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomConvert_BSplineSurfaceKnotSplitting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomConvert_BSplineSurfaceKnotSplitting(Geom_BSplineSurface BasisSurface, int UContinuityRange, int VContinuityRange) {
    this(OccJavaJNI.new_GeomConvert_BSplineSurfaceKnotSplitting(Geom_BSplineSurface.getCPtr(BasisSurface), BasisSurface, UContinuityRange, VContinuityRange), true);
  }

  public int NbUSplits() {
    return OccJavaJNI.GeomConvert_BSplineSurfaceKnotSplitting_NbUSplits(swigCPtr, this);
  }

  public int NbVSplits() {
    return OccJavaJNI.GeomConvert_BSplineSurfaceKnotSplitting_NbVSplits(swigCPtr, this);
  }

  public void Splitting(int[] USplit, int[] VSplit) {
    OccJavaJNI.GeomConvert_BSplineSurfaceKnotSplitting_Splitting(swigCPtr, this, USplit, VSplit);
  }

  public int USplitValue(int UIndex) {
    return OccJavaJNI.GeomConvert_BSplineSurfaceKnotSplitting_USplitValue(swigCPtr, this, UIndex);
  }

  public int VSplitValue(int VIndex) {
    return OccJavaJNI.GeomConvert_BSplineSurfaceKnotSplitting_VSplitValue(swigCPtr, this, VIndex);
  }

}
