/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI_ExtremaCurveSurface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI_ExtremaCurveSurface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI_ExtremaCurveSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI_ExtremaCurveSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomAPI_ExtremaCurveSurface() {
    this(OccJavaJNI.new_GeomAPI_ExtremaCurveSurface__SWIG_0(), true);
  }

  public GeomAPI_ExtremaCurveSurface(Geom_Curve Curve, Geom_Surface Surface) {
    this(OccJavaJNI.new_GeomAPI_ExtremaCurveSurface__SWIG_1(Geom_Curve.getCPtr(Curve), Curve, Geom_Surface.getCPtr(Surface), Surface), true);
  }

  public GeomAPI_ExtremaCurveSurface(Geom_Curve Curve, Geom_Surface Surface, double Wmin, double Wmax, double Umin, double Umax, double Vmin, double Vmax) {
    this(OccJavaJNI.new_GeomAPI_ExtremaCurveSurface__SWIG_2(Geom_Curve.getCPtr(Curve), Curve, Geom_Surface.getCPtr(Surface), Surface, Wmin, Wmax, Umin, Umax, Vmin, Vmax), true);
  }

  public void Init(Geom_Curve Curve, Geom_Surface Surface) {
    OccJavaJNI.GeomAPI_ExtremaCurveSurface_Init__SWIG_0(swigCPtr, this, Geom_Curve.getCPtr(Curve), Curve, Geom_Surface.getCPtr(Surface), Surface);
  }

  public void Init(Geom_Curve Curve, Geom_Surface Surface, double Wmin, double Wmax, double Umin, double Umax, double Vmin, double Vmax) {
    OccJavaJNI.GeomAPI_ExtremaCurveSurface_Init__SWIG_1(swigCPtr, this, Geom_Curve.getCPtr(Curve), Curve, Geom_Surface.getCPtr(Surface), Surface, Wmin, Wmax, Umin, Umax, Vmin, Vmax);
  }

  public int NbExtrema() {
    return OccJavaJNI.GeomAPI_ExtremaCurveSurface_NbExtrema(swigCPtr, this);
  }

  public void Points(int Index, double[] P1, double[] P2) {
    OccJavaJNI.GeomAPI_ExtremaCurveSurface_Points(swigCPtr, this, Index, P1, P2);
  }

  public void Parameters(int Index, double W, double U, double V) {
    OccJavaJNI.GeomAPI_ExtremaCurveSurface_Parameters(swigCPtr, this, Index, W, U, V);
  }

  public double Distance(int Index) {
    return OccJavaJNI.GeomAPI_ExtremaCurveSurface_Distance(swigCPtr, this, Index);
  }

  public void NearestPoints(double[] PC, double[] PS) {
    OccJavaJNI.GeomAPI_ExtremaCurveSurface_NearestPoints(swigCPtr, this, PC, PS);
  }

  public void LowerDistanceParameters(double W, double U, double V) {
    OccJavaJNI.GeomAPI_ExtremaCurveSurface_LowerDistanceParameters(swigCPtr, this, W, U, V);
  }

  public double LowerDistance() {
    return OccJavaJNI.GeomAPI_ExtremaCurveSurface_LowerDistance(swigCPtr, this);
  }

}
