/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_CartesianPoint extends Geom_Point {
  private long swigCPtr;

  public Geom_CartesianPoint(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_CartesianPoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_CartesianPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_CartesianPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_CartesianPoint(double[] P) {
    this(OccJavaJNI.new_Geom_CartesianPoint__SWIG_0(P), true);
  }

  public Geom_CartesianPoint(double X, double Y, double Z) {
    this(OccJavaJNI.new_Geom_CartesianPoint__SWIG_1(X, Y, Z), true);
  }

  public void SetCoord(double X, double Y, double Z) {
    OccJavaJNI.Geom_CartesianPoint_SetCoord(swigCPtr, this, X, Y, Z);
  }

  public void SetPnt(double[] P) {
    OccJavaJNI.Geom_CartesianPoint_SetPnt(swigCPtr, this, P);
  }

  public void SetX(double X) {
    OccJavaJNI.Geom_CartesianPoint_SetX(swigCPtr, this, X);
  }

  public void SetY(double Y) {
    OccJavaJNI.Geom_CartesianPoint_SetY(swigCPtr, this, Y);
  }

  public void SetZ(double Z) {
    OccJavaJNI.Geom_CartesianPoint_SetZ(swigCPtr, this, Z);
  }

  public void Coord(double[] X, double[] Y, double[] Z) {
    OccJavaJNI.Geom_CartesianPoint_Coord(swigCPtr, this, X, Y, Z);
  }

  public double[] Pnt() {
	return OccJavaJNI.Geom_CartesianPoint_Pnt(swigCPtr, this);
}

  public double X() {
    return OccJavaJNI.Geom_CartesianPoint_X(swigCPtr, this);
  }

  public double Y() {
    return OccJavaJNI.Geom_CartesianPoint_Y(swigCPtr, this);
  }

  public double Z() {
    return OccJavaJNI.Geom_CartesianPoint_Z(swigCPtr, this);
  }

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_CartesianPoint_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
