/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Circle extends Geom_Conic {
  private long swigCPtr;

  public Geom_Circle(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Circle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Circle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Circle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_Circle(GP_Circ C) {
    this(OccJavaJNI.new_Geom_Circle__SWIG_0(GP_Circ.getCPtr(C), C), true);
  }

  public Geom_Circle(double[] A2, double Radius) {
    this(OccJavaJNI.new_Geom_Circle__SWIG_1(A2, Radius), true);
  }

  public void SetCirc(GP_Circ C) {
    OccJavaJNI.Geom_Circle_SetCirc(swigCPtr, this, GP_Circ.getCPtr(C), C);
  }

  public void SetRadius(double R) {
    OccJavaJNI.Geom_Circle_SetRadius(swigCPtr, this, R);
  }

  public GP_Circ Circ() {
    return new GP_Circ(OccJavaJNI.Geom_Circle_Circ(swigCPtr, this), true);
  }

  public double Radius() {
    return OccJavaJNI.Geom_Circle_Radius(swigCPtr, this);
  }

  public double ReversedParameter(double U) {
    return OccJavaJNI.Geom_Circle_ReversedParameter(swigCPtr, this, U);
  }

  public double Eccentricity() {
    return OccJavaJNI.Geom_Circle_Eccentricity(swigCPtr, this);
  }

  public double FirstParameter() {
    return OccJavaJNI.Geom_Circle_FirstParameter(swigCPtr, this);
  }

  public double LastParameter() {
    return OccJavaJNI.Geom_Circle_LastParameter(swigCPtr, this);
  }

  public boolean IsClosed() {
	return OccJavaJNI.Geom_Circle_IsClosed(swigCPtr, this);
}

  public boolean IsPeriodic() {
	return OccJavaJNI.Geom_Circle_IsPeriodic(swigCPtr, this);
}

  public void D0(double U, double[] P) {
    OccJavaJNI.Geom_Circle_D0(swigCPtr, this, U, P);
  }

  public void D1(double U, double[] P, double[] V1) {
    OccJavaJNI.Geom_Circle_D1(swigCPtr, this, U, P, V1);
  }

  public void D2(double U, double[] P, double[] V1, double[] V2) {
    OccJavaJNI.Geom_Circle_D2(swigCPtr, this, U, P, V1, V2);
  }

  public void D3(double U, double[] P, double[] V1, double[] V2, double[] V3) {
    OccJavaJNI.Geom_Circle_D3(swigCPtr, this, U, P, V1, V2, V3);
  }

  public double[] DN(double U, int N) {
	return OccJavaJNI.Geom_Circle_DN(swigCPtr, this, U, N);
}

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_Circle_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
