/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Line extends Geom_Curve {
  private long swigCPtr;

  public Geom_Line(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Line_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Line obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Line(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_Line(double[] A1) {
    this(OccJavaJNI.new_Geom_Line__SWIG_0(A1), true);
  }

  public Geom_Line(GP_Lin L) {
    this(OccJavaJNI.new_Geom_Line__SWIG_1(GP_Lin.getCPtr(L), L), true);
  }

  public Geom_Line(double[] P, double[] V) {
    this(OccJavaJNI.new_Geom_Line__SWIG_2(P, V), true);
  }

  public void SetLin(GP_Lin L) {
    OccJavaJNI.Geom_Line_SetLin(swigCPtr, this, GP_Lin.getCPtr(L), L);
  }

  public void SetDirection(double[] V) {
    OccJavaJNI.Geom_Line_SetDirection(swigCPtr, this, V);
  }

  public void SetLocation(double[] P) {
    OccJavaJNI.Geom_Line_SetLocation(swigCPtr, this, P);
  }

  public void SetPosition(double[] A1) {
    OccJavaJNI.Geom_Line_SetPosition(swigCPtr, this, A1);
  }

  public GP_Lin Lin() {
    return new GP_Lin(OccJavaJNI.Geom_Line_Lin(swigCPtr, this), true);
  }

  public double[] Position() {
	return OccJavaJNI.Geom_Line_Position(swigCPtr, this);
}

  public void Reverse() {
    OccJavaJNI.Geom_Line_Reverse(swigCPtr, this);
  }

  public double ReversedParameter(double U) {
    return OccJavaJNI.Geom_Line_ReversedParameter(swigCPtr, this, U);
  }

  public double FirstParameter() {
    return OccJavaJNI.Geom_Line_FirstParameter(swigCPtr, this);
  }

  public double LastParameter() {
    return OccJavaJNI.Geom_Line_LastParameter(swigCPtr, this);
  }

  public boolean IsClosed() {
	return OccJavaJNI.Geom_Line_IsClosed(swigCPtr, this);
}

  public boolean IsPeriodic() {
	return OccJavaJNI.Geom_Line_IsPeriodic(swigCPtr, this);
}

  public GeomAbs_Shape Continuity() {
    return GeomAbs_Shape.swigToEnum(OccJavaJNI.Geom_Line_Continuity(swigCPtr, this));
  }

  public boolean IsCN(int N) {
	return OccJavaJNI.Geom_Line_IsCN(swigCPtr, this, N);
}

  public void D0(double U, double[] P) {
    OccJavaJNI.Geom_Line_D0(swigCPtr, this, U, P);
  }

  public void D1(double U, double[] P, double[] V1) {
    OccJavaJNI.Geom_Line_D1(swigCPtr, this, U, P, V1);
  }

  public void D2(double U, double[] P, double[] V1, double[] V2) {
    OccJavaJNI.Geom_Line_D2(swigCPtr, this, U, P, V1, V2);
  }

  public void D3(double U, double[] P, double[] V1, double[] V2, double[] V3) {
    OccJavaJNI.Geom_Line_D3(swigCPtr, this, U, P, V1, V2, V3);
  }

  public double[] DN(double U, int N) {
	return OccJavaJNI.Geom_Line_DN(swigCPtr, this, U, N);
}

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_Line_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

  public double TransformedParameter(double U, GP_Trsf T) {
    return OccJavaJNI.Geom_Line_TransformedParameter(swigCPtr, this, U, GP_Trsf.getCPtr(T), T);
  }

  public double ParametricTransformation(GP_Trsf T) {
    return OccJavaJNI.Geom_Line_ParametricTransformation(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
