/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomFill_Pipe {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomFill_Pipe(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomFill_Pipe obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomFill_Pipe(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomFill_Pipe() {
    this(OccJavaJNI.new_GeomFill_Pipe__SWIG_0(), true);
  }

  public GeomFill_Pipe(Geom_Curve Path, double Radius) {
    this(OccJavaJNI.new_GeomFill_Pipe__SWIG_1(Geom_Curve.getCPtr(Path), Path, Radius), true);
  }

  public GeomFill_Pipe(Geom2d_Curve Path, Geom_Surface Support, Geom_Curve FirstSect) {
    this(OccJavaJNI.new_GeomFill_Pipe__SWIG_2(Geom2d_Curve.getCPtr(Path), Path, Geom_Surface.getCPtr(Support), Support, Geom_Curve.getCPtr(FirstSect), FirstSect), true);
  }

  public GeomFill_Pipe(Geom_Curve Path, Geom_Curve FirstSect, double[] Dir) {
    this(OccJavaJNI.new_GeomFill_Pipe__SWIG_3(Geom_Curve.getCPtr(Path), Path, Geom_Curve.getCPtr(FirstSect), FirstSect, Dir), true);
  }

  public GeomFill_Pipe(Geom_Curve Path, Geom_Curve FirstSect, Geom_Curve LastSect) {
    this(OccJavaJNI.new_GeomFill_Pipe__SWIG_4(Geom_Curve.getCPtr(Path), Path, Geom_Curve.getCPtr(FirstSect), FirstSect, Geom_Curve.getCPtr(LastSect), LastSect), true);
  }

  public GeomFill_Pipe(Geom_Curve Path, Geom_Curve Curve1, Geom_Curve Curve2, double Radius) {
    this(OccJavaJNI.new_GeomFill_Pipe__SWIG_5(Geom_Curve.getCPtr(Path), Path, Geom_Curve.getCPtr(Curve1), Curve1, Geom_Curve.getCPtr(Curve2), Curve2, Radius), true);
  }

  public void Init(Geom_Curve Path, double Radius) {
    OccJavaJNI.GeomFill_Pipe_Init__SWIG_0(swigCPtr, this, Geom_Curve.getCPtr(Path), Path, Radius);
  }

  public void Init(Geom2d_Curve Path, Geom_Surface Support, Geom_Curve FirstSect) {
    OccJavaJNI.GeomFill_Pipe_Init__SWIG_1(swigCPtr, this, Geom2d_Curve.getCPtr(Path), Path, Geom_Surface.getCPtr(Support), Support, Geom_Curve.getCPtr(FirstSect), FirstSect);
  }

  public void Init(Geom_Curve Path, Geom_Curve FirstSect, double[] Dir) {
    OccJavaJNI.GeomFill_Pipe_Init__SWIG_2(swigCPtr, this, Geom_Curve.getCPtr(Path), Path, Geom_Curve.getCPtr(FirstSect), FirstSect, Dir);
  }

  public void Init(Geom_Curve Path, Geom_Curve FirstSect, Geom_Curve LastSect) {
    OccJavaJNI.GeomFill_Pipe_Init__SWIG_3(swigCPtr, this, Geom_Curve.getCPtr(Path), Path, Geom_Curve.getCPtr(FirstSect), FirstSect, Geom_Curve.getCPtr(LastSect), LastSect);
  }

  public void Perform(boolean WithParameters, boolean myPolynomial) {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_0(swigCPtr, this, WithParameters, myPolynomial);
  }

  public void Perform(boolean WithParameters) {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_1(swigCPtr, this, WithParameters);
  }

  public void Perform() {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_2(swigCPtr, this);
  }

  public void Perform(double Tol, boolean Polynomial, GeomAbs_Shape Conti, int MaxDegree, int NbMaxSegment) {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_3(swigCPtr, this, Tol, Polynomial, Conti.swigValue(), MaxDegree, NbMaxSegment);
  }

  public void Perform(double Tol, boolean Polynomial, GeomAbs_Shape Conti, int MaxDegree) {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_4(swigCPtr, this, Tol, Polynomial, Conti.swigValue(), MaxDegree);
  }

  public void Perform(double Tol, boolean Polynomial, GeomAbs_Shape Conti) {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_5(swigCPtr, this, Tol, Polynomial, Conti.swigValue());
  }

  public void Perform(double Tol, boolean Polynomial) {
    OccJavaJNI.GeomFill_Pipe_Perform__SWIG_6(swigCPtr, this, Tol, Polynomial);
  }

  public Geom_Surface Surface() {
    return new Geom_Surface(OccJavaJNI.GeomFill_Pipe_Surface(swigCPtr, this), false);
  }

  public boolean ExchangeUV() {
	return OccJavaJNI.GeomFill_Pipe_ExchangeUV(swigCPtr, this);
}

  public void GenerateParticularCase(boolean B) {
    OccJavaJNI.GeomFill_Pipe_GenerateParticularCase__SWIG_0(swigCPtr, this, B);
  }

  public boolean GenerateParticularCase() {
	return OccJavaJNI.GeomFill_Pipe_GenerateParticularCase__SWIG_1(swigCPtr, this);
}

  public double ErrorOnSurf() {
    return OccJavaJNI.GeomFill_Pipe_ErrorOnSurf(swigCPtr, this);
  }

}
