/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_ElementarySurface extends Geom_Surface {
  private long swigCPtr;

  public Geom_ElementarySurface(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_ElementarySurface_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_ElementarySurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_ElementarySurface(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void SetAxis(double[] A1) {
    OccJavaJNI.Geom_ElementarySurface_SetAxis(swigCPtr, this, A1);
  }

  public void SetLocation(double[] Loc) {
    OccJavaJNI.Geom_ElementarySurface_SetLocation(swigCPtr, this, Loc);
  }

  public void SetPosition(double[] A3) {
    OccJavaJNI.Geom_ElementarySurface_SetPosition(swigCPtr, this, A3);
  }

  public double[] Axis() {
	return OccJavaJNI.Geom_ElementarySurface_Axis(swigCPtr, this);
}

  public double[] Location() {
	return OccJavaJNI.Geom_ElementarySurface_Location(swigCPtr, this);
}

  public double[] Position() {
	return OccJavaJNI.Geom_ElementarySurface_Position(swigCPtr, this);
}

  public void UReverse() {
    OccJavaJNI.Geom_ElementarySurface_UReverse(swigCPtr, this);
  }

  public double UReversedParameter(double U) {
    return OccJavaJNI.Geom_ElementarySurface_UReversedParameter(swigCPtr, this, U);
  }

  public void VReverse() {
    OccJavaJNI.Geom_ElementarySurface_VReverse(swigCPtr, this);
  }

  public double VReversedParameter(double V) {
    return OccJavaJNI.Geom_ElementarySurface_VReversedParameter(swigCPtr, this, V);
  }

  public GeomAbs_Shape Continuity() {
    return GeomAbs_Shape.swigToEnum(OccJavaJNI.Geom_ElementarySurface_Continuity(swigCPtr, this));
  }

  public boolean IsCNu(int N) {
	return OccJavaJNI.Geom_ElementarySurface_IsCNu(swigCPtr, this, N);
}

  public boolean IsCNv(int N) {
	return OccJavaJNI.Geom_ElementarySurface_IsCNv(swigCPtr, this, N);
}

}
