/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Direction extends Geom_Vector {
  private long swigCPtr;

  public Geom_Direction(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Direction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Direction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Direction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_Direction(double X, double Y, double Z) {
    this(OccJavaJNI.new_Geom_Direction__SWIG_0(X, Y, Z), true);
  }

  public Geom_Direction(double[] V) {
    this(OccJavaJNI.new_Geom_Direction__SWIG_1(V), true);
  }

  public void SetCoord(double X, double Y, double Z) {
    OccJavaJNI.Geom_Direction_SetCoord(swigCPtr, this, X, Y, Z);
  }

  public void SetDir(double[] V) {
    OccJavaJNI.Geom_Direction_SetDir(swigCPtr, this, V);
  }

  public void SetX(double X) {
    OccJavaJNI.Geom_Direction_SetX(swigCPtr, this, X);
  }

  public void SetY(double Y) {
    OccJavaJNI.Geom_Direction_SetY(swigCPtr, this, Y);
  }

  public void SetZ(double Z) {
    OccJavaJNI.Geom_Direction_SetZ(swigCPtr, this, Z);
  }

  public double[] Dir() {
	return OccJavaJNI.Geom_Direction_Dir(swigCPtr, this);
}

  public double SquareMagnitude() {
    return OccJavaJNI.Geom_Direction_SquareMagnitude(swigCPtr, this);
  }

  public void Cross(Geom_Vector Other) {
    OccJavaJNI.Geom_Direction_Cross(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public void CrossCross(Geom_Vector V1, Geom_Vector V2) {
    OccJavaJNI.Geom_Direction_CrossCross(swigCPtr, this, Geom_Vector.getCPtr(V1), V1, Geom_Vector.getCPtr(V2), V2);
  }

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_Direction_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
