/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomConvert_ApproxSurface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomConvert_ApproxSurface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomConvert_ApproxSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomConvert_ApproxSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomConvert_ApproxSurface(Geom_Surface Surf, double Tol3d, GeomAbs_Shape UContinuity, GeomAbs_Shape VContinuity, int MaxDegU, int MaxDegV, int MaxSegments, int PrecisCode) {
    this(OccJavaJNI.new_GeomConvert_ApproxSurface(Geom_Surface.getCPtr(Surf), Surf, Tol3d, UContinuity.swigValue(), VContinuity.swigValue(), MaxDegU, MaxDegV, MaxSegments, PrecisCode), true);
  }

  public Geom_BSplineSurface Surface() {
    return new Geom_BSplineSurface(OccJavaJNI.GeomConvert_ApproxSurface_Surface(swigCPtr, this), true);
  }

  public boolean IsDone() {
	return OccJavaJNI.GeomConvert_ApproxSurface_IsDone(swigCPtr, this);
}

  public boolean HasResult() {
	return OccJavaJNI.GeomConvert_ApproxSurface_HasResult(swigCPtr, this);
}

  public double MaxError() {
    return OccJavaJNI.GeomConvert_ApproxSurface_MaxError(swigCPtr, this);
  }

}
