/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Conic extends Geom_Curve {
  private long swigCPtr;

  public Geom_Conic(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Conic_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Conic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Conic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void SetAxis(double[] A1) {
    OccJavaJNI.Geom_Conic_SetAxis(swigCPtr, this, A1);
  }

  public void SetLocation(double[] P) {
    OccJavaJNI.Geom_Conic_SetLocation(swigCPtr, this, P);
  }

  public void SetPosition(double[] A2) {
    OccJavaJNI.Geom_Conic_SetPosition(swigCPtr, this, A2);
  }

  public double[] Axis() {
	return OccJavaJNI.Geom_Conic_Axis(swigCPtr, this);
}

  public double Eccentricity() {
    return OccJavaJNI.Geom_Conic_Eccentricity(swigCPtr, this);
  }

  public double[] Location() {
	return OccJavaJNI.Geom_Conic_Location(swigCPtr, this);
}

  public double[] Position() {
	return OccJavaJNI.Geom_Conic_Position(swigCPtr, this);
}

  public double[] XAxis() {
	return OccJavaJNI.Geom_Conic_XAxis(swigCPtr, this);
}

  public double[] YAxis() {
	return OccJavaJNI.Geom_Conic_YAxis(swigCPtr, this);
}

  public void Reverse() {
    OccJavaJNI.Geom_Conic_Reverse(swigCPtr, this);
  }

  public double ReversedParameter(double U) {
    return OccJavaJNI.Geom_Conic_ReversedParameter(swigCPtr, this, U);
  }

  public GeomAbs_Shape Continuity() {
    return GeomAbs_Shape.swigToEnum(OccJavaJNI.Geom_Conic_Continuity(swigCPtr, this));
  }

  public boolean IsCN(int N) {
	return OccJavaJNI.Geom_Conic_IsCN(swigCPtr, this, N);
}

}
