/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Plane extends Geom_ElementarySurface {
  private long swigCPtr;

  public Geom_Plane(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Plane_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Plane obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Plane(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_Plane(double[] Pl) {
    this(OccJavaJNI.new_Geom_Plane__SWIG_0(Pl), true);
  }

  public Geom_Plane(double[] P, double[] V) {
    this(OccJavaJNI.new_Geom_Plane__SWIG_1(P, V), true);
  }

  public Geom_Plane(double A, double B, double C, double D) {
    this(OccJavaJNI.new_Geom_Plane__SWIG_2(A, B, C, D), true);
  }

  public void SetPln(double[] Pl) {
    OccJavaJNI.Geom_Plane_SetPln(swigCPtr, this, Pl);
  }

  public double[] Pln() {
	return OccJavaJNI.Geom_Plane_Pln(swigCPtr, this);
}

  public void UReverse() {
    OccJavaJNI.Geom_Plane_UReverse(swigCPtr, this);
  }

  public double UReversedParameter(double U) {
    return OccJavaJNI.Geom_Plane_UReversedParameter(swigCPtr, this, U);
  }

  public void VReverse() {
    OccJavaJNI.Geom_Plane_VReverse(swigCPtr, this);
  }

  public double VReversedParameter(double V) {
    return OccJavaJNI.Geom_Plane_VReversedParameter(swigCPtr, this, V);
  }

  public void TransformParameters(double U, double V, GP_Trsf T) {
    OccJavaJNI.Geom_Plane_TransformParameters(swigCPtr, this, U, V, GP_Trsf.getCPtr(T), T);
  }

  public void Bounds(double U1, double U2, double V1, double V2) {
    OccJavaJNI.Geom_Plane_Bounds(swigCPtr, this, U1, U2, V1, V2);
  }

  public void Coefficients(double A, double B, double C, double D) {
    OccJavaJNI.Geom_Plane_Coefficients(swigCPtr, this, A, B, C, D);
  }

  public boolean IsUClosed() {
	return OccJavaJNI.Geom_Plane_IsUClosed(swigCPtr, this);
}

  public boolean IsVClosed() {
	return OccJavaJNI.Geom_Plane_IsVClosed(swigCPtr, this);
}

  public boolean IsUPeriodic() {
	return OccJavaJNI.Geom_Plane_IsUPeriodic(swigCPtr, this);
}

  public boolean IsVPeriodic() {
	return OccJavaJNI.Geom_Plane_IsVPeriodic(swigCPtr, this);
}

  public Geom_Curve UIso(double U) {
    return new Geom_Curve(OccJavaJNI.Geom_Plane_UIso(swigCPtr, this, U), true);
  }

  public Geom_Curve VIso(double V) {
    return new Geom_Curve(OccJavaJNI.Geom_Plane_VIso(swigCPtr, this, V), true);
  }

  public void D0(double U, double V, double[] P) {
    OccJavaJNI.Geom_Plane_D0(swigCPtr, this, U, V, P);
  }

  public void D1(double U, double V, double[] P, double[] D1U, double[] D1V) {
    OccJavaJNI.Geom_Plane_D1(swigCPtr, this, U, V, P, D1U, D1V);
  }

  public void D2(double U, double V, double[] P, double[] D1U, double[] D1V, double[] D2U, double[] D2V, double[] D2UV) {
    OccJavaJNI.Geom_Plane_D2(swigCPtr, this, U, V, P, D1U, D1V, D2U, D2V, D2UV);
  }

  public void D3(double U, double V, double[] P, double[] D1U, double[] D1V, double[] D2U, double[] D2V, double[] D2UV, double[] D3U, double[] D3V, double[] D3UUV, double[] D3UVV) {
    OccJavaJNI.Geom_Plane_D3(swigCPtr, this, U, V, P, D1U, D1V, D2U, D2V, D2UV, D3U, D3V, D3UUV, D3UVV);
  }

  public double[] DN(double U, double V, int Nu, int Nv) {
	return OccJavaJNI.Geom_Plane_DN(swigCPtr, this, U, V, Nu, Nv);
}

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_Plane_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
