/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI_ExtremaSurfaceSurface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI_ExtremaSurfaceSurface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI_ExtremaSurfaceSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI_ExtremaSurfaceSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomAPI_ExtremaSurfaceSurface() {
    this(OccJavaJNI.new_GeomAPI_ExtremaSurfaceSurface__SWIG_0(), true);
  }

  public GeomAPI_ExtremaSurfaceSurface(Geom_Surface S1, Geom_Surface S2) {
    this(OccJavaJNI.new_GeomAPI_ExtremaSurfaceSurface__SWIG_1(Geom_Surface.getCPtr(S1), S1, Geom_Surface.getCPtr(S2), S2), true);
  }

  public GeomAPI_ExtremaSurfaceSurface(Geom_Surface S1, Geom_Surface S2, double U1min, double U1max, double V1min, double V1max, double U2min, double U2max, double V2min, double V2max) {
    this(OccJavaJNI.new_GeomAPI_ExtremaSurfaceSurface__SWIG_2(Geom_Surface.getCPtr(S1), S1, Geom_Surface.getCPtr(S2), S2, U1min, U1max, V1min, V1max, U2min, U2max, V2min, V2max), true);
  }

  public void Init(Geom_Surface S1, Geom_Surface S2) {
    OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_Init__SWIG_0(swigCPtr, this, Geom_Surface.getCPtr(S1), S1, Geom_Surface.getCPtr(S2), S2);
  }

  public void Init(Geom_Surface S1, Geom_Surface S2, double U1min, double U1max, double V1min, double V1max, double U2min, double U2max, double V2min, double V2max) {
    OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_Init__SWIG_1(swigCPtr, this, Geom_Surface.getCPtr(S1), S1, Geom_Surface.getCPtr(S2), S2, U1min, U1max, V1min, V1max, U2min, U2max, V2min, V2max);
  }

  public int NbExtrema() {
    return OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_NbExtrema(swigCPtr, this);
  }

  public void Points(int Index, double[] P1, double[] P2) {
    OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_Points(swigCPtr, this, Index, P1, P2);
  }

  public void Parameters(int Index, double U1, double V1, double U2, double V2) {
    OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_Parameters(swigCPtr, this, Index, U1, V1, U2, V2);
  }

  public double Distance(int Index) {
    return OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_Distance(swigCPtr, this, Index);
  }

  public void NearestPoints(double[] P1, double[] P2) {
    OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_NearestPoints(swigCPtr, this, P1, P2);
  }

  public void LowerDistanceParameters(double U1, double V1, double U2, double V2) {
    OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_LowerDistanceParameters(swigCPtr, this, U1, V1, U2, V2);
  }

  public double LowerDistance() {
    return OccJavaJNI.GeomAPI_ExtremaSurfaceSurface_LowerDistance(swigCPtr, this);
  }

}
