/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_SweptSurface extends Geom_Surface {
  private long swigCPtr;

  public Geom_SweptSurface(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_SweptSurface_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_SweptSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_SweptSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GeomAbs_Shape Continuity() {
    return GeomAbs_Shape.swigToEnum(OccJavaJNI.Geom_SweptSurface_Continuity(swigCPtr, this));
  }

  public double[] Direction() {
	return OccJavaJNI.Geom_SweptSurface_Direction(swigCPtr, this);
}

  public Geom_Curve BasisCurve() {
    return new Geom_Curve(OccJavaJNI.Geom_SweptSurface_BasisCurve(swigCPtr, this), true);
  }

}
