/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Geom2d_Curve To2d(Geom_Curve C, double[] P) {
    return new Geom2d_Curve(OccJavaJNI.GeomAPI_To2d(swigCPtr, this, Geom_Curve.getCPtr(C), C, P), true);
  }

  public Geom_Curve To3d(Geom2d_Curve C, double[] P) {
    return new Geom_Curve(OccJavaJNI.GeomAPI_To3d(swigCPtr, this, Geom2d_Curve.getCPtr(C), C, P), true);
  }

  public GeomAPI() {
    this(OccJavaJNI.new_GeomAPI(), true);
  }

}
