/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_ToroidalSurface extends Geom_ElementarySurface {
  private long swigCPtr;

  public Geom_ToroidalSurface(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_ToroidalSurface_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_ToroidalSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_ToroidalSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Geom_ToroidalSurface(double[] A3, double MajorRadius, double MinorRadius) {
    this(OccJavaJNI.new_Geom_ToroidalSurface__SWIG_0(A3, MajorRadius, MinorRadius), true);
  }

  public Geom_ToroidalSurface(GP_Torus T) {
    this(OccJavaJNI.new_Geom_ToroidalSurface__SWIG_1(GP_Torus.getCPtr(T), T), true);
  }

  public void SetMajorRadius(double MajorRadius) {
    OccJavaJNI.Geom_ToroidalSurface_SetMajorRadius(swigCPtr, this, MajorRadius);
  }

  public void SetMinorRadius(double MinorRadius) {
    OccJavaJNI.Geom_ToroidalSurface_SetMinorRadius(swigCPtr, this, MinorRadius);
  }

  public void SetTorus(GP_Torus T) {
    OccJavaJNI.Geom_ToroidalSurface_SetTorus(swigCPtr, this, GP_Torus.getCPtr(T), T);
  }

  public GP_Torus Torus() {
    return new GP_Torus(OccJavaJNI.Geom_ToroidalSurface_Torus(swigCPtr, this), true);
  }

  public double UReversedParameter(double U) {
    return OccJavaJNI.Geom_ToroidalSurface_UReversedParameter(swigCPtr, this, U);
  }

  public double VReversedParameter(double V) {
    return OccJavaJNI.Geom_ToroidalSurface_VReversedParameter(swigCPtr, this, V);
  }

  public double Area() {
    return OccJavaJNI.Geom_ToroidalSurface_Area(swigCPtr, this);
  }

  public void Bounds(double U1, double U2, double V1, double V2) {
    OccJavaJNI.Geom_ToroidalSurface_Bounds(swigCPtr, this, U1, U2, V1, V2);
  }

  public void Coefficients(double[] Coef) {
    OccJavaJNI.Geom_ToroidalSurface_Coefficients(swigCPtr, this, Coef);
  }

  public double MajorRadius() {
    return OccJavaJNI.Geom_ToroidalSurface_MajorRadius(swigCPtr, this);
  }

  public double MinorRadius() {
    return OccJavaJNI.Geom_ToroidalSurface_MinorRadius(swigCPtr, this);
  }

  public double Volume() {
    return OccJavaJNI.Geom_ToroidalSurface_Volume(swigCPtr, this);
  }

  public boolean IsUClosed() {
	return OccJavaJNI.Geom_ToroidalSurface_IsUClosed(swigCPtr, this);
}

  public boolean IsVClosed() {
	return OccJavaJNI.Geom_ToroidalSurface_IsVClosed(swigCPtr, this);
}

  public boolean IsUPeriodic() {
	return OccJavaJNI.Geom_ToroidalSurface_IsUPeriodic(swigCPtr, this);
}

  public boolean IsVPeriodic() {
	return OccJavaJNI.Geom_ToroidalSurface_IsVPeriodic(swigCPtr, this);
}

  public Geom_Curve UIso(double U) {
    return new Geom_Curve(OccJavaJNI.Geom_ToroidalSurface_UIso(swigCPtr, this, U), true);
  }

  public Geom_Curve VIso(double V) {
    return new Geom_Curve(OccJavaJNI.Geom_ToroidalSurface_VIso(swigCPtr, this, V), true);
  }

  public void D0(double U, double V, double[] P) {
    OccJavaJNI.Geom_ToroidalSurface_D0(swigCPtr, this, U, V, P);
  }

  public void D1(double U, double V, double[] P, double[] D1U, double[] D1V) {
    OccJavaJNI.Geom_ToroidalSurface_D1(swigCPtr, this, U, V, P, D1U, D1V);
  }

  public void D2(double U, double V, double[] P, double[] D1U, double[] D1V, double[] D2U, double[] D2V, double[] D2UV) {
    OccJavaJNI.Geom_ToroidalSurface_D2(swigCPtr, this, U, V, P, D1U, D1V, D2U, D2V, D2UV);
  }

  public void D3(double U, double V, double[] P, double[] D1U, double[] D1V, double[] D2U, double[] D2V, double[] D2UV, double[] D3U, double[] D3V, double[] D3UUV, double[] D3UVV) {
    OccJavaJNI.Geom_ToroidalSurface_D3(swigCPtr, this, U, V, P, D1U, D1V, D2U, D2V, D2UV, D3U, D3V, D3UUV, D3UVV);
  }

  public double[] DN(double U, double V, int Nu, int Nv) {
	return OccJavaJNI.Geom_ToroidalSurface_DN(swigCPtr, this, U, V, Nu, Nv);
}

  public void Transform(GP_Trsf T) {
    OccJavaJNI.Geom_ToroidalSurface_Transform(swigCPtr, this, GP_Trsf.getCPtr(T), T);
  }

}
