/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI_ExtremaCurveCurve {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI_ExtremaCurveCurve(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI_ExtremaCurveCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI_ExtremaCurveCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomAPI_ExtremaCurveCurve() {
    this(OccJavaJNI.new_GeomAPI_ExtremaCurveCurve__SWIG_0(), true);
  }

  public GeomAPI_ExtremaCurveCurve(Geom_Curve C1, Geom_Curve C2) {
    this(OccJavaJNI.new_GeomAPI_ExtremaCurveCurve__SWIG_1(Geom_Curve.getCPtr(C1), C1, Geom_Curve.getCPtr(C2), C2), true);
  }

  public GeomAPI_ExtremaCurveCurve(Geom_Curve C1, Geom_Curve C2, double U1min, double U1max, double U2min, double U2max) {
    this(OccJavaJNI.new_GeomAPI_ExtremaCurveCurve__SWIG_2(Geom_Curve.getCPtr(C1), C1, Geom_Curve.getCPtr(C2), C2, U1min, U1max, U2min, U2max), true);
  }

  public void Init(Geom_Curve C1, Geom_Curve C2) {
    OccJavaJNI.GeomAPI_ExtremaCurveCurve_Init__SWIG_0(swigCPtr, this, Geom_Curve.getCPtr(C1), C1, Geom_Curve.getCPtr(C2), C2);
  }

  public void Init(Geom_Curve C1, Geom_Curve C2, double U1min, double U1max, double U2min, double U2max) {
    OccJavaJNI.GeomAPI_ExtremaCurveCurve_Init__SWIG_1(swigCPtr, this, Geom_Curve.getCPtr(C1), C1, Geom_Curve.getCPtr(C2), C2, U1min, U1max, U2min, U2max);
  }

  public int NbExtrema() {
    return OccJavaJNI.GeomAPI_ExtremaCurveCurve_NbExtrema(swigCPtr, this);
  }

  public void Points(int Index, double[] P1, double[] P2) {
    OccJavaJNI.GeomAPI_ExtremaCurveCurve_Points(swigCPtr, this, Index, P1, P2);
  }

  public void Parameters(int Index, double U1, double U2) {
    OccJavaJNI.GeomAPI_ExtremaCurveCurve_Parameters(swigCPtr, this, Index, U1, U2);
  }

  public double Distance(int Index) {
    return OccJavaJNI.GeomAPI_ExtremaCurveCurve_Distance(swigCPtr, this, Index);
  }

  public void NearestPoints(double[] P1, double[] P2) {
    OccJavaJNI.GeomAPI_ExtremaCurveCurve_NearestPoints(swigCPtr, this, P1, P2);
  }

  public void LowerDistanceParameters(double U1, double U2) {
    OccJavaJNI.GeomAPI_ExtremaCurveCurve_LowerDistanceParameters(swigCPtr, this, U1, U2);
  }

  public double LowerDistance() {
    return OccJavaJNI.GeomAPI_ExtremaCurveCurve_LowerDistance(swigCPtr, this);
  }

  public boolean TotalNearestPoints(double[] P1, double[] P2) {
	return OccJavaJNI.GeomAPI_ExtremaCurveCurve_TotalNearestPoints(swigCPtr, this, P1, P2);
}

  public boolean TotalLowerDistanceParameters(double U1, double U2) {
	return OccJavaJNI.GeomAPI_ExtremaCurveCurve_TotalLowerDistanceParameters(swigCPtr, this, U1, U2);
}

  public double TotalLowerDistance() {
    return OccJavaJNI.GeomAPI_ExtremaCurveCurve_TotalLowerDistance(swigCPtr, this);
  }

}
