/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI_IntCS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI_IntCS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI_IntCS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI_IntCS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomAPI_IntCS() {
    this(OccJavaJNI.new_GeomAPI_IntCS__SWIG_0(), true);
  }

  public GeomAPI_IntCS(Geom_Curve C, Geom_Surface S) {
    this(OccJavaJNI.new_GeomAPI_IntCS__SWIG_1(Geom_Curve.getCPtr(C), C, Geom_Surface.getCPtr(S), S), true);
  }

  public void Perform(Geom_Curve C, Geom_Surface S) {
    OccJavaJNI.GeomAPI_IntCS_Perform(swigCPtr, this, Geom_Curve.getCPtr(C), C, Geom_Surface.getCPtr(S), S);
  }

  public boolean IsDone() {
	return OccJavaJNI.GeomAPI_IntCS_IsDone(swigCPtr, this);
}

  public int NbPoints() {
    return OccJavaJNI.GeomAPI_IntCS_NbPoints(swigCPtr, this);
  }

  public double[] Point(int Index) {
	return OccJavaJNI.GeomAPI_IntCS_Point(swigCPtr, this, Index);
}

  public void Parameters(int Index, double U, double V, double W) {
    OccJavaJNI.GeomAPI_IntCS_Parameters__SWIG_0(swigCPtr, this, Index, U, V, W);
  }

  public int NbSegments() {
    return OccJavaJNI.GeomAPI_IntCS_NbSegments(swigCPtr, this);
  }

  public Geom_Curve Segment(int Index) {
    return new Geom_Curve(OccJavaJNI.GeomAPI_IntCS_Segment(swigCPtr, this, Index), true);
  }

  public void Parameters(int Index, double U1, double V1, double U2, double V2) {
    OccJavaJNI.GeomAPI_IntCS_Parameters__SWIG_1(swigCPtr, this, Index, U1, V1, U2, V2);
  }

}
