/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_BoundedCurve extends Geom_Curve {
  private long swigCPtr;

  public Geom_BoundedCurve(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_BoundedCurve_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_BoundedCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_BoundedCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double[] EndPoint() {
	return OccJavaJNI.Geom_BoundedCurve_EndPoint(swigCPtr, this);
}

  public double[] StartPoint() {
	return OccJavaJNI.Geom_BoundedCurve_StartPoint(swigCPtr, this);
}

}
