/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class Geom_Vector extends Geom_Geometry {
  private long swigCPtr;

  public Geom_Vector(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.Geom_Vector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Geom_Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_Geom_Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void Reverse() {
    OccJavaJNI.Geom_Vector_Reverse(swigCPtr, this);
  }

  public double Angle(Geom_Vector Other) {
    return OccJavaJNI.Geom_Vector_Angle(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public double AngleWithRef(Geom_Vector Other, Geom_Vector VRef) {
    return OccJavaJNI.Geom_Vector_AngleWithRef(swigCPtr, this, Geom_Vector.getCPtr(Other), Other, Geom_Vector.getCPtr(VRef), VRef);
  }

  public void Coord(double[] X, double[] Y, double[] Z) {
    OccJavaJNI.Geom_Vector_Coord(swigCPtr, this, X, Y, Z);
  }

  public double Magnitude() {
    return OccJavaJNI.Geom_Vector_Magnitude(swigCPtr, this);
  }

  public double SquareMagnitude() {
    return OccJavaJNI.Geom_Vector_SquareMagnitude(swigCPtr, this);
  }

  public double X() {
    return OccJavaJNI.Geom_Vector_X(swigCPtr, this);
  }

  public double Y() {
    return OccJavaJNI.Geom_Vector_Y(swigCPtr, this);
  }

  public double Z() {
    return OccJavaJNI.Geom_Vector_Z(swigCPtr, this);
  }

  public void Cross(Geom_Vector Other) {
    OccJavaJNI.Geom_Vector_Cross(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public void CrossCross(Geom_Vector V1, Geom_Vector V2) {
    OccJavaJNI.Geom_Vector_CrossCross(swigCPtr, this, Geom_Vector.getCPtr(V1), V1, Geom_Vector.getCPtr(V2), V2);
  }

  public double Dot(Geom_Vector Other) {
    return OccJavaJNI.Geom_Vector_Dot(swigCPtr, this, Geom_Vector.getCPtr(Other), Other);
  }

  public double DotCross(Geom_Vector V1, Geom_Vector V2) {
    return OccJavaJNI.Geom_Vector_DotCross(swigCPtr, this, Geom_Vector.getCPtr(V1), V1, Geom_Vector.getCPtr(V2), V2);
  }

  public double[] Vec() {
	return OccJavaJNI.Geom_Vector_Vec(swigCPtr, this);
}

}
