/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI_Interpolate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI_Interpolate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI_Interpolate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI_Interpolate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomAPI_Interpolate(double[] Points, boolean PeriodicFlag, double Tolerance) {
    this(OccJavaJNI.new_GeomAPI_Interpolate(Points, PeriodicFlag, Tolerance), true);
  }

  public void Load(double[] InitialTangent, double[] FinalTangent, boolean Scale) {
    OccJavaJNI.GeomAPI_Interpolate_Load__SWIG_0(swigCPtr, this, InitialTangent, FinalTangent, Scale);
  }

  public void Load(double[] InitialTangent, double[] FinalTangent) {
    OccJavaJNI.GeomAPI_Interpolate_Load__SWIG_1(swigCPtr, this, InitialTangent, FinalTangent);
  }

  public void Load(double[] Tangents, boolean[] TangentFlags, boolean Scale) {
    OccJavaJNI.GeomAPI_Interpolate_Load__SWIG_2(swigCPtr, this, Tangents, TangentFlags, Scale);
  }

  public void Load(double[] Tangents, boolean[] TangentFlags) {
    OccJavaJNI.GeomAPI_Interpolate_Load__SWIG_3(swigCPtr, this, Tangents, TangentFlags);
  }

  public void Perform() {
    OccJavaJNI.GeomAPI_Interpolate_Perform(swigCPtr, this);
  }

  public Geom_BSplineCurve Curve() {
    return new Geom_BSplineCurve(OccJavaJNI.GeomAPI_Interpolate_Curve(swigCPtr, this), false);
  }

  public boolean IsDone() {
	return OccJavaJNI.GeomAPI_Interpolate_IsDone(swigCPtr, this);
}

}
