/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GeomAPI_PointsToBSplineSurface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GeomAPI_PointsToBSplineSurface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeomAPI_PointsToBSplineSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GeomAPI_PointsToBSplineSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeomAPI_PointsToBSplineSurface() {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_0(), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, int DegMin, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_1(TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin, DegMax, Continuity.swigValue(), Tol3D), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, int DegMin, int DegMax, GeomAbs_Shape Continuity) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_2(TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin, DegMax, Continuity.swigValue()), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, int DegMin, int DegMax) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_3(TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin, DegMax), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, int DegMin) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_4(TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_5(TColgp_Array2OfPnt.getCPtr(Points), Points), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_6(TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin, DegMax, Continuity.swigValue(), Tol3D), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin, int DegMax, GeomAbs_Shape Continuity) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_7(TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin, DegMax, Continuity.swigValue()), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin, int DegMax) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_8(TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin, DegMax), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_9(TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_10(TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue()), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_11(TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3, DegMax, Continuity.swigValue(), Tol3D), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3, int DegMax, GeomAbs_Shape Continuity) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_12(TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3, DegMax, Continuity.swigValue()), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3, int DegMax) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_13(TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3, DegMax), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_14(TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_15(TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin, DegMax, Continuity.swigValue(), Tol3D), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin, int DegMax, GeomAbs_Shape Continuity) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_16(TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin, DegMax, Continuity.swigValue()), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin, int DegMax) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_17(TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin, DegMax), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_18(TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin), true);
  }

  public GeomAPI_PointsToBSplineSurface(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY) {
    this(OccJavaJNI.new_GeomAPI_PointsToBSplineSurface__SWIG_19(TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY), true);
  }

  public void Init(TColgp_Array2OfPnt Points, int DegMin, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_0(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin, DegMax, Continuity.swigValue(), Tol3D);
  }

  public void Init(TColgp_Array2OfPnt Points, int DegMin, int DegMax, GeomAbs_Shape Continuity) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_1(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin, DegMax, Continuity.swigValue());
  }

  public void Init(TColgp_Array2OfPnt Points, int DegMin, int DegMax) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_2(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin, DegMax);
  }

  public void Init(TColgp_Array2OfPnt Points, int DegMin) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_3(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, DegMin);
  }

  public void Init(TColgp_Array2OfPnt Points) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_4(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points);
  }

  public void Interpolate(TColgp_Array2OfPnt Points) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Interpolate__SWIG_0(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points);
  }

  public void Interpolate(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Interpolate__SWIG_1(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue());
  }

  public void Init(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_5(swigCPtr, this, TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin, DegMax, Continuity.swigValue(), Tol3D);
  }

  public void Init(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin, int DegMax, GeomAbs_Shape Continuity) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_6(swigCPtr, this, TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin, DegMax, Continuity.swigValue());
  }

  public void Init(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin, int DegMax) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_7(swigCPtr, this, TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin, DegMax);
  }

  public void Init(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY, int DegMin) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_8(swigCPtr, this, TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY, DegMin);
  }

  public void Init(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_9(swigCPtr, this, TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY);
  }

  public void Interpolate(TColStd_Array2OfReal ZPoints, double X0, double dX, double Y0, double dY) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Interpolate__SWIG_2(swigCPtr, this, TColStd_Array2OfReal.getCPtr(ZPoints), ZPoints, X0, dX, Y0, dY);
  }

  public void Init(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_10(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin, DegMax, Continuity.swigValue(), Tol3D);
  }

  public void Init(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin, int DegMax, GeomAbs_Shape Continuity) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_11(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin, DegMax, Continuity.swigValue());
  }

  public void Init(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin, int DegMax) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_12(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin, DegMax);
  }

  public void Init(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType, int DegMin) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_13(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue(), DegMin);
  }

  public void Init(TColgp_Array2OfPnt Points, Approx_ParametrizationType ParType) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_14(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, ParType.swigValue());
  }

  public void Init(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3, int DegMax, GeomAbs_Shape Continuity, double Tol3D) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_15(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3, DegMax, Continuity.swigValue(), Tol3D);
  }

  public void Init(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3, int DegMax, GeomAbs_Shape Continuity) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_16(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3, DegMax, Continuity.swigValue());
  }

  public void Init(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3, int DegMax) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_17(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3, DegMax);
  }

  public void Init(TColgp_Array2OfPnt Points, double Weight1, double Weight2, double Weight3) {
    OccJavaJNI.GeomAPI_PointsToBSplineSurface_Init__SWIG_18(swigCPtr, this, TColgp_Array2OfPnt.getCPtr(Points), Points, Weight1, Weight2, Weight3);
  }

  public Geom_BSplineSurface Surface() {
    return new Geom_BSplineSurface(OccJavaJNI.GeomAPI_PointsToBSplineSurface_Surface(swigCPtr, this), false);
  }

  public boolean IsDone() {
	return OccJavaJNI.GeomAPI_PointsToBSplineSurface_IsDone(swigCPtr, this);
}

}
