/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GP_Lin {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GP_Lin(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GP_Lin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GP_Lin(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GP_Lin() {
    this(OccJavaJNI.new_GP_Lin__SWIG_0(), true);
  }

  public GP_Lin(double[] A1) {
    this(OccJavaJNI.new_GP_Lin__SWIG_1(A1), true);
  }

  public GP_Lin(double[] P, double[] V) {
    this(OccJavaJNI.new_GP_Lin__SWIG_2(P, V), true);
  }

}
