/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GP_Trsf2d {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GP_Trsf2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GP_Trsf2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GP_Trsf2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GP_Trsf2d() {
    this(OccJavaJNI.new_GP_Trsf2d__SWIG_0(), true);
  }

  public GP_Trsf2d(GP_Trsf T) {
    this(OccJavaJNI.new_GP_Trsf2d__SWIG_1(GP_Trsf.getCPtr(T), T), true);
  }

}
