/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class LocOpe_WiresOnShape extends LocOpe_ProjectedWires {
  private long swigCPtr;

  public LocOpe_WiresOnShape(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.LocOpe_WiresOnShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(LocOpe_WiresOnShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_LocOpe_WiresOnShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void InitEdgeIterator() {
    OccJavaJNI.LocOpe_WiresOnShape_InitEdgeIterator(swigCPtr, this);
  }

  public boolean OnEdge(TopoDS_Edge E) {
	return OccJavaJNI.LocOpe_WiresOnShape_OnEdge(swigCPtr, this, TopoDS_Edge.getCPtr(E), E);
}

  public void NextEdge() {
    OccJavaJNI.LocOpe_WiresOnShape_NextEdge(swigCPtr, this);
  }

  public boolean MoreEdge() {
	return OccJavaJNI.LocOpe_WiresOnShape_MoreEdge(swigCPtr, this);
}

  public boolean IsDone() {
	return OccJavaJNI.LocOpe_WiresOnShape_IsDone(swigCPtr, this);
}

}
