/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class LocOpe_Spliter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LocOpe_Spliter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LocOpe_Spliter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_LocOpe_Spliter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LocOpe_Spliter() {
    this(OccJavaJNI.new_LocOpe_Spliter__SWIG_0(), true);
  }

  public LocOpe_Spliter(TopoDS_Shape S) {
    this(OccJavaJNI.new_LocOpe_Spliter__SWIG_1(TopoDS_Shape.getCPtr(S), S), true);
  }

  public void Init(TopoDS_Shape S) {
    OccJavaJNI.LocOpe_Spliter_Init(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
  }

}
