/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class ShapeFix_Face extends ShapeFix_Root {
  private long swigCPtr;

  public ShapeFix_Face(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.ShapeFix_Face_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ShapeFix_Face obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_ShapeFix_Face(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ShapeFix_Face() {
    this(OccJavaJNI.new_ShapeFix_Face__SWIG_0(), true);
  }

  public ShapeFix_Face(TopoDS_Face face) {
    this(OccJavaJNI.new_ShapeFix_Face__SWIG_1(TopoDS_Face.getCPtr(face), face), true);
  }

  public void ClearModes() {
    OccJavaJNI.ShapeFix_Face_ClearModes(swigCPtr, this);
  }

  public void Init(TopoDS_Face face) {
    OccJavaJNI.ShapeFix_Face_Init__SWIG_0(swigCPtr, this, TopoDS_Face.getCPtr(face), face);
  }

  public void Init(Geom_Surface surf, double preci, boolean fwd) {
    OccJavaJNI.ShapeFix_Face_Init__SWIG_1(swigCPtr, this, Geom_Surface.getCPtr(surf), surf, preci, fwd);
  }

  public void Init(Geom_Surface surf, double preci) {
    OccJavaJNI.ShapeFix_Face_Init__SWIG_2(swigCPtr, this, Geom_Surface.getCPtr(surf), surf, preci);
  }

  public void setPrecision(double preci) {
    OccJavaJNI.ShapeFix_Face_setPrecision(swigCPtr, this, preci);
  }

  public void SetMinTolerance(double mintol) {
    OccJavaJNI.ShapeFix_Face_SetMinTolerance(swigCPtr, this, mintol);
  }

  public void SetMaxTolerance(double maxtol) {
    OccJavaJNI.ShapeFix_Face_SetMaxTolerance(swigCPtr, this, maxtol);
  }

  public int FixWireMode() {
    return OccJavaJNI.ShapeFix_Face_FixWireMode(swigCPtr, this);
  }

  public int FixOrientationMode() {
    return OccJavaJNI.ShapeFix_Face_FixOrientationMode(swigCPtr, this);
  }

  public int FixAddNaturalBoundMode() {
    return OccJavaJNI.ShapeFix_Face_FixAddNaturalBoundMode(swigCPtr, this);
  }

  public int FixMissingSeamMode() {
    return OccJavaJNI.ShapeFix_Face_FixMissingSeamMode(swigCPtr, this);
  }

  public int FixSmallAreaWireMode() {
    return OccJavaJNI.ShapeFix_Face_FixSmallAreaWireMode(swigCPtr, this);
  }

  public int FixIntersectingWiresMode() {
    return OccJavaJNI.ShapeFix_Face_FixIntersectingWiresMode(swigCPtr, this);
  }

  public int FixLoopWiresMode() {
    return OccJavaJNI.ShapeFix_Face_FixLoopWiresMode(swigCPtr, this);
  }

  public int FixSplitFaceMode() {
    return OccJavaJNI.ShapeFix_Face_FixSplitFaceMode(swigCPtr, this);
  }

  public int AutoCorrectPrecisionMode() {
    return OccJavaJNI.ShapeFix_Face_AutoCorrectPrecisionMode(swigCPtr, this);
  }

  public TopoDS_Face Face() {
    return new TopoDS_Face(OccJavaJNI.ShapeFix_Face_Face(swigCPtr, this), true);
  }

  public TopoDS_Shape Result() {
    long cPtr = OccJavaJNI.ShapeFix_Face_Result(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public void Add(TopoDS_Wire wire) {
    OccJavaJNI.ShapeFix_Face_Add(swigCPtr, this, TopoDS_Wire.getCPtr(wire), wire);
  }

  public boolean Perform() {
	return OccJavaJNI.ShapeFix_Face_Perform(swigCPtr, this);
}

  public boolean FixOrientation() {
	return OccJavaJNI.ShapeFix_Face_FixOrientation(swigCPtr, this);
}

  public boolean FixAddNaturalBound() {
	return OccJavaJNI.ShapeFix_Face_FixAddNaturalBound(swigCPtr, this);
}

  public boolean FixMissingSeam() {
	return OccJavaJNI.ShapeFix_Face_FixMissingSeam(swigCPtr, this);
}

  public boolean FixSmallAreaWire() {
	return OccJavaJNI.ShapeFix_Face_FixSmallAreaWire(swigCPtr, this);
}

  public boolean FixIntersectingWires() {
	return OccJavaJNI.ShapeFix_Face_FixIntersectingWires(swigCPtr, this);
}

  public boolean FixWiresTwoCoincEdges() {
	return OccJavaJNI.ShapeFix_Face_FixWiresTwoCoincEdges(swigCPtr, this);
}

}
