/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class SWIGTYPE_p_Handle_TCollection_HAsciiString {
  private long swigCPtr;

  protected SWIGTYPE_p_Handle_TCollection_HAsciiString(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_Handle_TCollection_HAsciiString() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_Handle_TCollection_HAsciiString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

