/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class TColgp_Array2OfPnt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TColgp_Array2OfPnt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TColgp_Array2OfPnt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_TColgp_Array2OfPnt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TColgp_Array2OfPnt(int R1, int R2, int C1, int C2) {
    this(OccJavaJNI.new_TColgp_Array2OfPnt__SWIG_0(R1, R2, C1, C2), true);
  }

  public TColgp_Array2OfPnt(double[] Item, int R1, int R2, int C1, int C2) {
    this(OccJavaJNI.new_TColgp_Array2OfPnt__SWIG_1(Item, R1, R2, C1, C2), true);
  }

  public void Init(double[] V) {
    OccJavaJNI.TColgp_Array2OfPnt_Init(swigCPtr, this, V);
  }

  public void Destroy() {
    OccJavaJNI.TColgp_Array2OfPnt_Destroy(swigCPtr, this);
  }

  public int ColLength() {
    return OccJavaJNI.TColgp_Array2OfPnt_ColLength(swigCPtr, this);
  }

  public int RowLength() {
    return OccJavaJNI.TColgp_Array2OfPnt_RowLength(swigCPtr, this);
  }

  public int LowerCol() {
    return OccJavaJNI.TColgp_Array2OfPnt_LowerCol(swigCPtr, this);
  }

  public int LowerRow() {
    return OccJavaJNI.TColgp_Array2OfPnt_LowerRow(swigCPtr, this);
  }

  public int UpperCol() {
    return OccJavaJNI.TColgp_Array2OfPnt_UpperCol(swigCPtr, this);
  }

  public int UpperRow() {
    return OccJavaJNI.TColgp_Array2OfPnt_UpperRow(swigCPtr, this);
  }

  public void SetValue(int Row, int Col, double[] Value) {
    OccJavaJNI.TColgp_Array2OfPnt_SetValue(swigCPtr, this, Row, Col, Value);
  }

  public double[] Value(int Row, int Col) {
	return OccJavaJNI.TColgp_Array2OfPnt_Value(swigCPtr, this, Row, Col);
}

  public double[] ChangeValue(int Row, int Col) {
	return OccJavaJNI.TColgp_Array2OfPnt_ChangeValue(swigCPtr, this, Row, Col);
}

}
